# ==============================================================================
# Altera (Intel) SPI IP Core — Comprehensive Timing Constraints
# ==============================================================================
#
# Target IP       : Intel (Altera) SPI Core (altera_avalon_spi)
# Compatible With : Quartus Prime (Standard / Pro)
# SDC Version     : Synopsys Design Constraints (IEEE 1735)
#
# This file provides production-quality timing constraints for the Altera SPI
# IP core in both Master and Slave configurations. Every section includes a
# rationale so that the constraints can be adapted to any board-level design.
#
# ------------------------------------------------------------------------------
# TABLE OF CONTENTS
# ------------------------------------------------------------------------------
#   Section 1  – User-Configurable Parameters
#   Section 2  – System Clock Definition
#   Section 3  – SPI Generated Clock (Master Mode)
#   Section 4  – SPI Input Delay Constraints (Master Mode – MISO Path)
#   Section 5  – SPI Output Delay Constraints (Master Mode – MOSI / SS_n Path)
#   Section 6  – SPI Input Delay Constraints (Slave Mode – MOSI / SS_n Path)
#   Section 7  – SPI Output Delay Constraints (Slave Mode – MISO Path)
#   Section 8  – Clock Domain Crossing Constraints
#   Section 9  – False Path Declarations
#   Section 10 – Multicycle Path Declarations
#   Section 11 – Clock Uncertainty & Jitter
#   Section 12 – CPOL / CPHA Mode-Specific Adjustments
#   Section 13 – Pin Location & I/O Standard Constraints
#   Section 14 – Additional Recommendations
# ==============================================================================


# ==============================================================================
# SECTION 1 — USER-CONFIGURABLE PARAMETERS
# ==============================================================================
# Adjust these values to match your actual board-level design.  All times are
# in nanoseconds unless stated otherwise.
#
# Naming conventions used throughout:
#   SYS_CLK_FREQ   – Frequency of the Avalon system/bus clock driving the SPI
#                     core's internal logic.
#   SPI_CLK_FREQ   – Frequency of the SPI serial clock (SCLK) as seen on the
#                     external pin.  For master mode this is generated by the
#                     core via a clock divider; for slave mode it is supplied by
#                     the external SPI master.
#   Tpcb_*         – Trace propagation delay on the PCB (one-way).
#   Tco_*          – Clock-to-output delay of the external SPI device.
#   Tsu_*          – Setup time requirement of the external SPI device.
#   Th_*           – Hold time requirement of the external SPI device.
# ==============================================================================

set SYS_CLK_FREQ       50.0     ;# MHz – Avalon bus clock frequency
set SPI_CLK_FREQ       25.0     ;# MHz – SPI serial clock frequency

set SYS_CLK_PERIOD     [expr {1000.0 / $SYS_CLK_FREQ}]   ;# ns
set SPI_CLK_PERIOD     [expr {1000.0 / $SPI_CLK_FREQ}]    ;# ns

# --- Board-level trace delays (one-way) ---
set Tpcb_clk           0.5      ;# ns – PCB delay on SCLK trace
set Tpcb_data_out      0.5      ;# ns – PCB delay on MOSI / SS_n traces
set Tpcb_data_in       0.5      ;# ns – PCB delay on MISO trace

# --- External SPI slave device timing (for Master-mode analysis) ---
set Tco_slave_max      8.0      ;# ns – Max clock-to-output of slave (MISO)
set Tco_slave_min      2.0      ;# ns – Min clock-to-output of slave (MISO)
set Tsu_slave          5.0      ;# ns – Setup time of slave (MOSI input)
set Th_slave           2.0      ;# ns – Hold time of slave (MOSI input)

# --- External SPI master device timing (for Slave-mode analysis) ---
set Tco_master_max     8.0      ;# ns – Max clock-to-output of master (MOSI)
set Tco_master_min     2.0      ;# ns – Min clock-to-output of master (MOSI)
set Tsu_master         5.0      ;# ns – Setup time of master (MISO input)
set Th_master          2.0      ;# ns – Hold time of master (MISO input)

# --- FPGA I/O timing (from datasheet; varies by device & I/O standard) ---
set Tco_fpga_max       6.5      ;# ns – Max FPGA clock-to-output
set Tco_fpga_min       1.0      ;# ns – Min FPGA clock-to-output
set Tsu_fpga           1.5      ;# ns – FPGA input register setup requirement
set Th_fpga            0.5      ;# ns – FPGA input register hold requirement

# --- Clock jitter & uncertainty ---
set clk_jitter         0.1      ;# ns – Peak-to-peak clock jitter
set board_skew         0.2      ;# ns – Board-level clock skew allowance

# --- SPI signal names (update to match your design hierarchy) ---
set SPI_SCLK_PIN       "spi_sclk"
set SPI_MOSI_PIN       "spi_mosi"
set SPI_MISO_PIN       "spi_miso"
set SPI_SS_PIN         "spi_ss_n"

# --- SPI core instance path (update to match your Qsys/Platform Designer hierarchy) ---
set SPI_INST           "u0|spi_0"


# ==============================================================================
# SECTION 2 — SYSTEM CLOCK DEFINITION
# ==============================================================================
# The system clock drives the Avalon-MM interface of the SPI core.  All
# register-to-register paths inside the SPI core are clocked by this clock.
#
# EXPLANATION:
#   create_clock tells the TimeQuest (Timing Analyzer) the period and waveform
#   of the clock applied to the given pin.  The -waveform argument specifies
#   the rising and falling edges within one period (here, a 50 % duty cycle).
# ==============================================================================

create_clock -name sys_clk \
    -period $SYS_CLK_PERIOD \
    -waveform [list 0.0 [expr {$SYS_CLK_PERIOD / 2.0}]] \
    [get_ports clk]


# ==============================================================================
# SECTION 3 — SPI GENERATED CLOCK (MASTER MODE)
# ==============================================================================
# In master mode the SPI core derives SCLK from the system clock through an
# internal clock divider.  The generated clock must be declared so that the
# Timing Analyzer can compute the correct launch/latch relationships for the
# MOSI (output) and MISO (input) paths.
#
# EXPLANATION:
#   create_generated_clock establishes a parent-child relationship between
#   sys_clk and spi_sclk.  The -divide_by factor must equal the SPI core's
#   configured clock divider (SYS_CLK_FREQ / SPI_CLK_FREQ).  This ensures that
#   all I/O timing analysis on the SPI bus uses the correct SCLK frequency.
#
# NOTE:
#   If you use the "Clock polarity" (CPOL) = 1 setting, add -invert to create
#   the inverted SCLK waveform.  See Section 12 for CPOL/CPHA adjustments.
# ==============================================================================

set spi_clk_div [expr {int($SYS_CLK_FREQ / $SPI_CLK_FREQ)}]

create_generated_clock -name spi_sclk \
    -source [get_ports clk] \
    -divide_by $spi_clk_div \
    [get_ports $SPI_SCLK_PIN]


# ==============================================================================
# SECTION 4 — SPI INPUT DELAY CONSTRAINTS (MASTER MODE – MISO PATH)
# ==============================================================================
# When the FPGA is the SPI master, the MISO signal is driven by the external
# slave device and sampled by the FPGA on a clock edge of SCLK.
#
# The round-trip timing budget for the MISO path is:
#
#   FPGA ──SCLK──▶ PCB ──▶ Slave ──Tco──▶ MISO ──▶ PCB ──▶ FPGA
#          Tpcb_clk                Tco           Tpcb_data_in
#
# set_input_delay defines the data arrival window relative to the clock edge
# at the FPGA pin.  The delay accounts for:
#   - PCB trace delay on SCLK (outbound)
#   - External slave's clock-to-output time (Tco)
#   - PCB trace delay on MISO (return)
#
# Max delay governs SETUP analysis; min delay governs HOLD analysis.
#
# EXPLANATION:
#   -max  = Tpcb_clk + Tco_slave_max + Tpcb_data_in
#           (latest the data could arrive after the launching SCLK edge)
#   -min  = Tpcb_clk + Tco_slave_min + Tpcb_data_in
#           (earliest the data could arrive — used for hold check)
#
#   -clock_fall is used when CPHA=0 (data launched on falling, captured on
#   rising).  Remove it or swap to -clock_rise for CPHA=1.  See Section 12.
# ==============================================================================

set miso_input_max [expr {$Tpcb_clk + $Tco_slave_max + $Tpcb_data_in}]
set miso_input_min [expr {$Tpcb_clk + $Tco_slave_min + $Tpcb_data_in}]

set_input_delay -clock spi_sclk \
    -max $miso_input_max \
    [get_ports $SPI_MISO_PIN]

set_input_delay -clock spi_sclk \
    -min $miso_input_min \
    [get_ports $SPI_MISO_PIN]

# For double-data-rate (DDR) SPI or when data is valid on both edges, add the
# complementary edge constraint:
#
# set_input_delay -clock spi_sclk -max $miso_input_max \
#     -clock_fall -add_delay [get_ports $SPI_MISO_PIN]
# set_input_delay -clock spi_sclk -min $miso_input_min \
#     -clock_fall -add_delay [get_ports $SPI_MISO_PIN]


# ==============================================================================
# SECTION 5 — SPI OUTPUT DELAY CONSTRAINTS (MASTER MODE – MOSI / SS_n PATH)
# ==============================================================================
# When the FPGA is the SPI master, it drives MOSI and SS_n.  The external slave
# samples MOSI on a SCLK edge.  The timing budget is:
#
#   FPGA ──MOSI──▶ PCB ──▶ Slave (setup / hold relative to SCLK at slave)
#
# Since both SCLK and MOSI originate from the FPGA, the relevant delays are
# the *difference* in PCB trace delays plus the slave's setup/hold times.
#
# EXPLANATION:
#   set_output_delay -max = Tpcb_data_out - Tpcb_clk + Tsu_slave
#     The maximum output delay is set so that data arrives at the slave with
#     enough margin before the capturing clock edge (setup requirement).
#
#   set_output_delay -min = -(Tpcb_clk - Tpcb_data_out + Th_slave)
#     The minimum output delay (often negative) ensures data is held long
#     enough after the capturing clock edge (hold requirement).  A negative
#     value means data may change *before* the clock edge arrives at the slave,
#     tightening hold.
# ==============================================================================

set mosi_output_max [expr {$Tpcb_data_out - $Tpcb_clk + $Tsu_slave}]
set mosi_output_min [expr {-($Tpcb_clk - $Tpcb_data_out + $Th_slave)}]

# MOSI output delay
set_output_delay -clock spi_sclk \
    -max $mosi_output_max \
    [get_ports $SPI_MOSI_PIN]

set_output_delay -clock spi_sclk \
    -min $mosi_output_min \
    [get_ports $SPI_MOSI_PIN]

# SS_n (chip select, directly tied to SCLK timing domain)
set_output_delay -clock spi_sclk \
    -max $mosi_output_max \
    [get_ports $SPI_SS_PIN]

set_output_delay -clock spi_sclk \
    -min $mosi_output_min \
    [get_ports $SPI_SS_PIN]


# ==============================================================================
# SECTION 6 — SPI INPUT DELAY CONSTRAINTS (SLAVE MODE – MOSI / SS_n PATH)
# ==============================================================================
# When the FPGA is the SPI slave, an external master drives SCLK, MOSI, and
# SS_n into the FPGA.  The SCLK from the master must first be declared as an
# external input clock, then input delays for MOSI and SS_n are set relative
# to that clock.
#
# EXPLANATION:
#   create_clock on the SCLK input pin treats the incoming serial clock as a
#   primary clock for timing analysis.  The -max/-min input delays represent
#   the skew between SCLK and MOSI/SS_n as they arrive at the FPGA pins, which
#   is determined by the external master's Tco and the differential PCB delay
#   between the SCLK trace and the data traces.
# ==============================================================================

# Uncomment and use this section when the FPGA is configured as SPI slave.

# create_clock -name spi_sclk_ext \
#     -period $SPI_CLK_PERIOD \
#     -waveform [list 0.0 [expr {$SPI_CLK_PERIOD / 2.0}]] \
#     [get_ports $SPI_SCLK_PIN]
#
# set slave_mosi_input_max [expr {$Tco_master_max + ($Tpcb_data_out - $Tpcb_clk)}]
# set slave_mosi_input_min [expr {$Tco_master_min + ($Tpcb_data_out - $Tpcb_clk)}]
#
# # MOSI input (slave receives data from master)
# set_input_delay -clock spi_sclk_ext \
#     -max $slave_mosi_input_max \
#     [get_ports $SPI_MOSI_PIN]
#
# set_input_delay -clock spi_sclk_ext \
#     -min $slave_mosi_input_min \
#     [get_ports $SPI_MOSI_PIN]
#
# # SS_n input (active-low chip select from master)
# set_input_delay -clock spi_sclk_ext \
#     -max $slave_mosi_input_max \
#     [get_ports $SPI_SS_PIN]
#
# set_input_delay -clock spi_sclk_ext \
#     -min $slave_mosi_input_min \
#     [get_ports $SPI_SS_PIN]


# ==============================================================================
# SECTION 7 — SPI OUTPUT DELAY CONSTRAINTS (SLAVE MODE – MISO PATH)
# ==============================================================================
# In slave mode the FPGA drives MISO back to the external master.  The master
# samples MISO on an SCLK edge.
#
# EXPLANATION:
#   The output delay is referenced to the external SCLK arriving at the FPGA.
#   The max delay must satisfy the master's setup requirement, and the min
#   delay must satisfy its hold requirement — both accounting for the
#   difference in PCB trace lengths between MISO and SCLK.
# ==============================================================================

# Uncomment and use this section when the FPGA is configured as SPI slave.

# set slave_miso_output_max [expr {$Tpcb_data_in - $Tpcb_clk + $Tsu_master}]
# set slave_miso_output_min [expr {-($Tpcb_clk - $Tpcb_data_in + $Th_master)}]
#
# set_output_delay -clock spi_sclk_ext \
#     -max $slave_miso_output_max \
#     [get_ports $SPI_MISO_PIN]
#
# set_output_delay -clock spi_sclk_ext \
#     -min $slave_miso_output_min \
#     [get_ports $SPI_MISO_PIN]


# ==============================================================================
# SECTION 8 — CLOCK DOMAIN CROSSING CONSTRAINTS
# ==============================================================================
# The SPI core has two clock domains:
#   1. sys_clk  – Avalon-MM / register-file side
#   2. spi_sclk – Serial I/O side
#
# Because spi_sclk is derived from sys_clk (master mode), the Timing Analyzer
# can automatically compute the relationship.  However, if the derivation is
# not cleanly recognized (e.g., the divider is implemented in fabric logic
# rather than a PLL), you should declare the crossing explicitly.
#
# EXPLANATION:
#   set_clock_groups -asynchronous tells the analyzer to skip timing analysis
#   between clocks that are truly asynchronous (e.g., an external slave-mode
#   SCLK vs. the system clock).
#
#   For master mode where spi_sclk is synchronously derived, you typically do
#   NOT need set_clock_groups; the generated clock relationship suffices.
#   The constraint below is provided for slave-mode or mixed-mode designs.
# ==============================================================================

# Uncomment for slave mode where spi_sclk_ext is asynchronous to sys_clk:
# set_clock_groups -asynchronous \
#     -group [get_clocks sys_clk] \
#     -group [get_clocks spi_sclk_ext]

# For master mode, the generated clock relationship is inherently synchronous.
# If TimeQuest still reports cross-domain violations on the divider logic,
# use set_false_path instead (see Section 9).


# ==============================================================================
# SECTION 9 — FALSE PATH DECLARATIONS
# ==============================================================================
# False paths remove timing requirements from paths that are not
# functionally exercised during normal operation.
#
# EXPLANATION:
#   1. Reset paths: The asynchronous reset (or synchronous reset release)
#      does not need to meet the full clock-to-clock timing.
#   2. Static configuration registers: The SPI core's configuration registers
#      (e.g., baud rate divider, CPOL, CPHA settings) are written once during
#      initialization and are static during SPI transactions.
#   3. SS_n to MISO: There is no direct register-to-register timing
#      relationship between the active-low chip-select output and the MISO
#      input — they are captured/driven on independent clock edges.
# ==============================================================================

# 9.1 – Reset false path
#        The reset signal is typically asynchronous or quasi-static; timing
#        from reset to any register is a false path for STA purposes.
set_false_path -from [get_ports reset_n]

# 9.2 – Static configuration registers
#        Paths from Avalon write-data to the SPI shift register that pass
#        through static configuration fields (clock divider, mode bits) are
#        written only at init time and need not be timed against spi_sclk.
#        Uncomment and adjust the register paths to your hierarchy:
# set_false_path -from [get_registers ${SPI_INST}|control_reg*] \
#                -to   [get_registers ${SPI_INST}|shift_reg*]

# 9.3 – Chip-select to data paths
#        SS_n assertion/de-assertion is separated from data transfers by
#        protocol-mandated idle time, so direct SS_n→MISO paths are false.
# set_false_path -from [get_ports $SPI_SS_PIN] -to [get_ports $SPI_MISO_PIN]


# ==============================================================================
# SECTION 10 — MULTICYCLE PATH DECLARATIONS
# ==============================================================================
# Multicycle paths arise when a signal is allowed more than one clock period
# to propagate from source to destination.
#
# EXPLANATION:
#   The SPI shift register is clocked at spi_sclk, which is slower than
#   sys_clk.  Paths from the Avalon data bus to the SPI shift register have
#   spi_clk_div system clock cycles to settle.  Declaring them as multicycle
#   paths gives the fitter more freedom and avoids over-constraining.
#
#   -setup N means the data has N clock edges (of the destination clock) to
#   arrive.  -hold (N-1) keeps the hold check aligned to the correct edge.
# ==============================================================================

# 10.1 – Avalon write-data → SPI TX shift register
#         Data is loaded into the shift register and then shifted out at the
#         slower SPI clock rate.  The transfer from sys_clk to spi_sclk takes
#         spi_clk_div system-clock cycles.
# set_multicycle_path -setup $spi_clk_div \
#     -from [get_clocks sys_clk] \
#     -to   [get_clocks spi_sclk]
# set_multicycle_path -hold [expr {$spi_clk_div - 1}] \
#     -from [get_clocks sys_clk] \
#     -to   [get_clocks spi_sclk]

# 10.2 – SPI RX shift register → Avalon read-data
#         The received data is assembled over multiple spi_sclk cycles and then
#         transferred to the Avalon domain.  The multicycle path reflects the
#         slower source clock.
# set_multicycle_path -setup $spi_clk_div \
#     -from [get_clocks spi_sclk] \
#     -to   [get_clocks sys_clk]
# set_multicycle_path -hold [expr {$spi_clk_div - 1}] \
#     -from [get_clocks spi_sclk] \
#     -to   [get_clocks sys_clk]


# ==============================================================================
# SECTION 11 — CLOCK UNCERTAINTY & JITTER
# ==============================================================================
# Clock uncertainty accounts for jitter on the clock source (PLL or
# oscillator), board-level skew between clock traces, and any intra-die
# variation not already modeled by the Timing Analyzer.
#
# EXPLANATION:
#   set_clock_uncertainty adds guard-band to both setup and hold checks:
#     -setup  : Reduces the available setup margin.
#     -hold   : Increases the required hold margin.
#
#   For inter-clock (sys_clk ↔ spi_sclk) transfers, the uncertainty may be
#   larger because both clock paths contribute jitter independently.  When
#   spi_sclk is a generated clock from the same PLL as sys_clk, their jitter
#   is correlated and the inter-clock uncertainty can be kept small.
# ==============================================================================

set total_uncertainty [expr {$clk_jitter + $board_skew}]

# Intra-clock uncertainty (same clock domain)
set_clock_uncertainty -setup $total_uncertainty [get_clocks sys_clk]
set_clock_uncertainty -hold  [expr {$total_uncertainty / 2.0}] [get_clocks sys_clk]

set_clock_uncertainty -setup $total_uncertainty [get_clocks spi_sclk]
set_clock_uncertainty -hold  [expr {$total_uncertainty / 2.0}] [get_clocks spi_sclk]

# Inter-clock uncertainty (sys_clk ↔ spi_sclk)
set_clock_uncertainty -setup $total_uncertainty \
    -from [get_clocks sys_clk] -to [get_clocks spi_sclk]
set_clock_uncertainty -hold  [expr {$total_uncertainty / 2.0}] \
    -from [get_clocks sys_clk] -to [get_clocks spi_sclk]
set_clock_uncertainty -setup $total_uncertainty \
    -from [get_clocks spi_sclk] -to [get_clocks sys_clk]
set_clock_uncertainty -hold  [expr {$total_uncertainty / 2.0}] \
    -from [get_clocks spi_sclk] -to [get_clocks sys_clk]


# ==============================================================================
# SECTION 12 — CPOL / CPHA MODE-SPECIFIC ADJUSTMENTS
# ==============================================================================
# The SPI protocol defines four modes based on Clock Polarity (CPOL) and
# Clock Phase (CPHA).  The correct launch/latch edge in the constraints must
# match the configured mode.
#
#   Mode 0 (CPOL=0, CPHA=0):
#     - SCLK idles low.
#     - Data is captured on the RISING  edge (first edge after SS_n asserts).
#     - Data is shifted out on the FALLING edge.
#     ➜ Default constraints above assume this mode.
#
#   Mode 1 (CPOL=0, CPHA=1):
#     - SCLK idles low.
#     - Data is shifted out on the RISING  edge.
#     - Data is captured on the FALLING edge.
#     ➜ Add -clock_fall to set_input_delay for MISO.
#     ➜ Add -clock_fall to set_output_delay for MOSI.
#
#   Mode 2 (CPOL=1, CPHA=0):
#     - SCLK idles high (inverted waveform).
#     - Data is captured on the FALLING edge (first edge after SS_n asserts).
#     - Data is shifted out on the RISING  edge.
#     ➜ Add -invert to create_generated_clock for spi_sclk.
#     ➜ Default -max/-min on rising edge becomes the falling edge capture.
#
#   Mode 3 (CPOL=1, CPHA=1):
#     - SCLK idles high (inverted waveform).
#     - Data is shifted out on the FALLING edge.
#     - Data is captured on the RISING  edge.
#     ➜ Add -invert to create_generated_clock.
#     ➜ Add -clock_fall to input/output delays.
#
# EXAMPLE — Switching to Mode 1 (CPOL=0, CPHA=1):
#
# set_input_delay -clock spi_sclk -max $miso_input_max \
#     -clock_fall [get_ports $SPI_MISO_PIN]
# set_input_delay -clock spi_sclk -min $miso_input_min \
#     -clock_fall [get_ports $SPI_MISO_PIN]
# set_output_delay -clock spi_sclk -max $mosi_output_max \
#     -clock_fall [get_ports $SPI_MOSI_PIN]
# set_output_delay -clock spi_sclk -min $mosi_output_min \
#     -clock_fall [get_ports $SPI_MOSI_PIN]
#
# EXAMPLE — Switching to Mode 2 (CPOL=1, CPHA=0):
#
# create_generated_clock -name spi_sclk \
#     -source [get_ports clk] \
#     -divide_by $spi_clk_div \
#     -invert \
#     [get_ports $SPI_SCLK_PIN]
# (then keep the default rising-edge input/output delay constraints)
#
# ==============================================================================


# ==============================================================================
# SECTION 13 — PIN LOCATION & I/O STANDARD CONSTRAINTS
# ==============================================================================
# These constraints are project-specific.  They are included here as templates
# to illustrate best practice: keeping I/O timing, placement, and standard
# constraints together for the SPI interface.
#
# EXPLANATION:
#   set_instance_assignment assigns physical properties to I/O pins.
#   The I/O standard affects the timing model used by TimeQuest for the pin's
#   output buffer delay (Tco) and input buffer delay (Tsu/Th).  Matching the
#   actual voltage standard is critical for accurate timing analysis.
#
# Common I/O standards for SPI:
#   "3.3-V LVTTL"   – Most common for 3.3 V SPI
#   "2.5 V"         – 2.5 V SPI
#   "1.8 V"         – Low-voltage SPI
#   "3.3-V LVCMOS"  – Alternative 3.3 V standard
# ==============================================================================

# Uncomment and update the PIN_xx values to match your pin assignment:

# set_location_assignment PIN_A1 -to $SPI_SCLK_PIN
# set_location_assignment PIN_A2 -to $SPI_MOSI_PIN
# set_location_assignment PIN_A3 -to $SPI_MISO_PIN
# set_location_assignment PIN_A4 -to $SPI_SS_PIN

# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to $SPI_SCLK_PIN
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to $SPI_MOSI_PIN
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to $SPI_MISO_PIN
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to $SPI_SS_PIN

# Drive strength and slew rate (optional, helps signal integrity):
# set_instance_assignment -name CURRENT_STRENGTH_NEW "8MA" -to $SPI_MOSI_PIN
# set_instance_assignment -name CURRENT_STRENGTH_NEW "8MA" -to $SPI_SCLK_PIN
# set_instance_assignment -name CURRENT_STRENGTH_NEW "8MA" -to $SPI_SS_PIN
# set_instance_assignment -name SLEW_RATE 1 -to $SPI_MOSI_PIN
# set_instance_assignment -name SLEW_RATE 1 -to $SPI_SCLK_PIN
# set_instance_assignment -name SLEW_RATE 1 -to $SPI_SS_PIN


# ==============================================================================
# SECTION 14 — ADDITIONAL RECOMMENDATIONS
# ==============================================================================
#
# 14.1  TIMING CLOSURE CHECKLIST
#       After applying these constraints, run the Timing Analyzer and verify:
#         ☐  No unconstrained paths on SPI I/O ports
#         ☐  Setup slack ≥ 0 on all SPI paths
#         ☐  Hold slack ≥ 0 on all SPI paths
#         ☐  No critical warnings about missing clocks or undefined delays
#
# 14.2  PLL USAGE
#       If your system clock is generated by a PLL, use derive_pll_clocks to
#       automatically create clock constraints for all PLL outputs:
#         derive_pll_clocks
#       Then reference the PLL output clock name instead of "clk" in the
#       create_generated_clock for spi_sclk.
#
# 14.3  DERIVE CLOCK UNCERTAINTY
#       Quartus can automatically compute clock uncertainty from PLL jitter
#       specifications when you use:
#         derive_clock_uncertainty
#       This may be more accurate than the manual set_clock_uncertainty in
#       Section 11 and is recommended when using Altera PLLs.
#
# 14.4  MULTI-SLAVE TOPOLOGIES
#       If the SPI master connects to multiple slaves, each slave's MISO path
#       may have different board delays.  Create separate input delay
#       constraints for each slave's MISO path using -add_delay:
#
#       set_input_delay -clock spi_sclk -max $miso_input_max_slave0 \
#           [get_ports miso_slave0]
#       set_input_delay -clock spi_sclk -max $miso_input_max_slave1 \
#           -add_delay [get_ports miso_slave1]
#
#       Similarly, individual SS_n lines may have different trace delays.
#
# 14.5  QUAD / DUAL SPI
#       For Quad-SPI or Dual-SPI configurations, apply the same input/output
#       delay methodology to all data lines (IO0, IO1, IO2, IO3).  In
#       bidirectional modes, constrain both input and output delays on each
#       data pin.
#
# 14.6  REPORT COMMANDS
#       Use these TimeQuest / Timing Analyzer commands to verify constraints:
#
#       report_clocks                              ;# List all clocks
#       report_clock_transfers                     ;# Show clock relationships
#       report_timing -from [get_ports $SPI_MISO_PIN] -setup -npaths 10
#       report_timing -from [get_ports $SPI_MISO_PIN] -hold  -npaths 10
#       report_timing -to   [get_ports $SPI_MOSI_PIN] -setup -npaths 10
#       report_timing -to   [get_ports $SPI_MOSI_PIN] -hold  -npaths 10
#       check_timing                               ;# Find unconstrained paths
#
# ==============================================================================
# END OF FILE
# ==============================================================================
