# ==============================================================================
# SDC Timing Constraints for Altera (Intel) SPI Master IP Core
# ==============================================================================
#
# Description:
#   This SDC file provides timing constraints for the Altera/Intel SPI Master
#   IP core (altera_avalon_spi). The SPI master generates the serial clock
#   (SCLK) and drives MOSI/SS_n outputs while sampling the MISO input.
#
# SPI Protocol Overview:
#   - SCLK : Serial clock, generated by the master from the system clock
#   - MOSI : Master Out Slave In (output from master)
#   - MISO : Master In Slave Out (input to master)
#   - SS_n : Slave Select, active-low chip select (output from master)
#
# SPI Modes (CPOL/CPHA combinations):
#   - Mode 0 (CPOL=0, CPHA=0): Data sampled on SCLK rising, shifted on falling
#   - Mode 1 (CPOL=0, CPHA=1): Data sampled on SCLK falling, shifted on rising
#   - Mode 2 (CPOL=1, CPHA=0): Data sampled on SCLK falling, shifted on rising
#   - Mode 3 (CPOL=1, CPHA=1): Data sampled on SCLK rising, shifted on falling
#
# Usage:
#   1. Adjust the hierarchy path variable SPI_MASTER_INST to match your design
#   2. Set SPI_SCLK_FREQ_MHZ to the desired SPI clock frequency
#   3. Update board-level delay values (Tpcb_*) based on your PCB layout
#   4. Adjust SPI_MODE if not using Mode 0
#   5. Source this file in your Quartus project or include via .qsf assignment
#
# Target Device : Intel/Altera FPGAs (Cyclone, Arria, Stratix families)
# Tool Version  : Quartus Prime 18.0+ / TimeQuest Timing Analyzer
# ==============================================================================


# ==============================================================================
# Section 1: User-Configurable Parameters
# ==============================================================================

# Hierarchical instance path to the SPI master IP in your design
set SPI_MASTER_INST "u_spi_master"

# System clock frequency (MHz) - the Avalon bus clock driving the SPI core
set SYS_CLK_FREQ_MHZ 50.0

# SPI serial clock frequency (MHz) - SCLK output frequency
# Typically the system clock divided by a programmable divider (2, 4, 8, ...)
set SPI_SCLK_FREQ_MHZ 25.0

# SPI mode selection (0, 1, 2, or 3) -- affects sampling/launch edge polarity
set SPI_MODE 0

# FPGA output pin names (directly mapped to top-level ports)
set SCLK_PORT  "spi_sclk"
set MOSI_PORT  "spi_mosi"
set MISO_PORT  "spi_miso"
set SS_N_PORT  "spi_ss_n"

# ------------------------------------------------------------------------------
# Board-Level Trace / PCB Delay Parameters (nanoseconds)
# These values must be characterized from your PCB layout or signal-integrity
# analysis. They represent the propagation delay from FPGA pin to SPI slave pin.
# ------------------------------------------------------------------------------

# PCB trace delay from FPGA SCLK pin to slave SCLK pin (ns)
set Tpcb_sclk 0.5

# PCB trace delay from FPGA MOSI pin to slave MOSI pin (ns)
set Tpcb_mosi 0.5

# PCB trace delay from slave MISO pin to FPGA MISO pin (ns)
set Tpcb_miso 0.5

# PCB trace delay from FPGA SS_n pin to slave SS_n pin (ns)
set Tpcb_ss_n 0.5

# SPI slave device timing parameters (from slave datasheet)
# Tco  : Slave clock-to-output time for MISO after SCLK edge (max)
# Tco_min : Slave clock-to-output time for MISO after SCLK edge (min)
# Tsu  : Slave setup time for MOSI data before SCLK sampling edge
# Th   : Slave hold time for MOSI data after SCLK sampling edge
# Tss  : Slave select setup time -- SS_n must be active before first SCLK edge
# Tsh  : Slave select hold time -- SS_n must remain active after last SCLK edge
set Tco_slave_max  8.0
set Tco_slave_min  0.0
set Tsu_slave      5.0
set Th_slave       2.0
set Tss_slave      5.0
set Tsh_slave      5.0


# ==============================================================================
# Section 2: System Clock Definition
# ==============================================================================

# Define the primary system clock that drives the SPI master core.
# This clock feeds the Avalon-MM interface and internal SPI logic.
# Adjust -name and -source as needed for your design.
set sys_clk_period [expr {1000.0 / $SYS_CLK_FREQ_MHZ}]

create_clock -name sys_clk \
    -period $sys_clk_period \
    [get_ports clk]


# ==============================================================================
# Section 3: SPI SCLK Generated Clock
# ==============================================================================

# The SPI master IP generates SCLK by dividing the system clock using an
# internal clock divider register. SCLK is output through an FPGA pin and
# serves as the timing reference for all SPI bus transfers.
#
# We define SCLK as a generated clock derived from the system clock.
# The division factor is sys_clk_freq / spi_sclk_freq.

set sclk_div_factor [expr {int($SYS_CLK_FREQ_MHZ / $SPI_SCLK_FREQ_MHZ)}]
set sclk_period     [expr {1000.0 / $SPI_SCLK_FREQ_MHZ}]

create_generated_clock -name spi_sclk_out \
    -source [get_ports clk] \
    -divide_by $sclk_div_factor \
    [get_ports $SCLK_PORT]

# Note: If SCLK is generated by a register inside the IP rather than directly
# from a PLL, the -source should reference the register's clock pin:
#   -source [get_pins ${SPI_MASTER_INST}|sclk_reg|clk]
# Adjust the -source to match the actual clock tree in your synthesized design.


# ==============================================================================
# Section 4: SCLK Virtual Clock for I/O Constraint Analysis
# ==============================================================================

# A virtual clock represents the SCLK as seen at the SPI slave device.
# This accounts for the board-level delay between the FPGA SCLK output and
# the slave's SCLK input. It is used as the reference clock for
# set_output_delay / set_input_delay constraints.

create_clock -name spi_sclk_virtual \
    -period $sclk_period


# ==============================================================================
# Section 5: Output Delay Constraints -- MOSI
# ==============================================================================

# MOSI is driven by the SPI master and captured by the SPI slave on the
# appropriate SCLK edge (depending on SPI mode).
#
# Output delay accounts for:
#   1. PCB trace delay from FPGA MOSI pin to slave MOSI pin (Tpcb_mosi)
#   2. Slave device setup time (Tsu_slave)
#   3. Clock skew: SCLK arrives at slave with Tpcb_sclk delay
#
# For set_output_delay -max:
#   delay_max = Tpcb_mosi + Tsu_slave - Tpcb_sclk
#   (Data must arrive at the slave Tsu before the sampling SCLK edge)
#
# For set_output_delay -min:
#   delay_min = Tpcb_mosi - Th_slave - Tpcb_sclk
#   (Data must be held for Th after the previous SCLK edge)

set mosi_output_delay_max [expr {$Tpcb_mosi + $Tsu_slave - $Tpcb_sclk}]
set mosi_output_delay_min [expr {$Tpcb_mosi - $Th_slave  - $Tpcb_sclk}]

set_output_delay -clock spi_sclk_virtual \
    -max $mosi_output_delay_max \
    [get_ports $MOSI_PORT]

set_output_delay -clock spi_sclk_virtual \
    -min $mosi_output_delay_min \
    [get_ports $MOSI_PORT]

# For SPI Modes 1 and 3, data is launched on the rising edge and captured
# on the falling edge (or vice versa). Add -clock_fall if the slave samples
# on the falling edge of SCLK.
if {$SPI_MODE == 1 || $SPI_MODE == 2} {
    set_output_delay -clock spi_sclk_virtual \
        -max $mosi_output_delay_max \
        -clock_fall \
        [get_ports $MOSI_PORT] -add_delay

    set_output_delay -clock spi_sclk_virtual \
        -min $mosi_output_delay_min \
        -clock_fall \
        [get_ports $MOSI_PORT] -add_delay
}


# ==============================================================================
# Section 6: Output Delay Constraints -- SS_n (Chip Select)
# ==============================================================================

# The slave select (SS_n) signal must be asserted before the first SCLK edge
# and held after the last SCLK edge of a transaction. We constrain it relative
# to the virtual SCLK.
#
# SS_n timing requirements:
#   -max: SS_n must be stable Tss_slave before the first SCLK edge
#   -min: SS_n must be held Tsh_slave after the last SCLK edge

set ss_output_delay_max [expr {$Tpcb_ss_n + $Tss_slave - $Tpcb_sclk}]
set ss_output_delay_min [expr {$Tpcb_ss_n - $Tsh_slave - $Tpcb_sclk}]

set_output_delay -clock spi_sclk_virtual \
    -max $ss_output_delay_max \
    [get_ports $SS_N_PORT]

set_output_delay -clock spi_sclk_virtual \
    -min $ss_output_delay_min \
    [get_ports $SS_N_PORT]


# ==============================================================================
# Section 7: Input Delay Constraints -- MISO
# ==============================================================================

# MISO is driven by the SPI slave after a SCLK edge and captured by the
# FPGA SPI master on the next (opposite) SCLK edge.
#
# Input delay accounts for:
#   1. PCB trace delay from FPGA SCLK pin to slave SCLK pin (Tpcb_sclk)
#   2. Slave clock-to-output delay (Tco_slave_max / Tco_slave_min)
#   3. PCB trace delay from slave MISO pin to FPGA MISO pin (Tpcb_miso)
#
# For set_input_delay -max:
#   delay_max = Tpcb_sclk + Tco_slave_max + Tpcb_miso
#   (Worst-case arrival time of MISO data at FPGA pin)
#
# For set_input_delay -min:
#   delay_min = Tpcb_sclk + Tco_slave_min + Tpcb_miso
#   (Best-case arrival time; used for hold analysis)

set miso_input_delay_max [expr {$Tpcb_sclk + $Tco_slave_max + $Tpcb_miso}]
set miso_input_delay_min [expr {$Tpcb_sclk + $Tco_slave_min + $Tpcb_miso}]

set_input_delay -clock spi_sclk_virtual \
    -max $miso_input_delay_max \
    [get_ports $MISO_PORT]

set_input_delay -clock spi_sclk_virtual \
    -min $miso_input_delay_min \
    [get_ports $MISO_PORT]

# For SPI Modes 0 and 3, data is launched by the slave on the falling edge
# and sampled by the master on the rising edge. For Modes 1 and 2, the
# opposite is true. Add -clock_fall for falling-edge-launched data.
if {$SPI_MODE == 0 || $SPI_MODE == 3} {
    set_input_delay -clock spi_sclk_virtual \
        -max $miso_input_delay_max \
        -clock_fall \
        [get_ports $MISO_PORT] -add_delay

    set_input_delay -clock spi_sclk_virtual \
        -min $miso_input_delay_min \
        -clock_fall \
        [get_ports $MISO_PORT] -add_delay
}


# ==============================================================================
# Section 8: Clock Groups and Asynchronous Clock Domain Crossings
# ==============================================================================

# If the SPI clock domain is asynchronous to other clocks in the design,
# declare them as exclusive or asynchronous clock groups to prevent invalid
# cross-domain timing analysis.

# set_clock_groups -asynchronous \
#     -group [get_clocks sys_clk] \
#     -group [get_clocks spi_sclk_virtual]

# Note: Do NOT set sys_clk and spi_sclk_out as asynchronous if SCLK is
# derived from sys_clk, as that would mask real timing issues in the
# divider logic. Only use -asynchronous for truly unrelated clock domains.


# ==============================================================================
# Section 9: False Paths
# ==============================================================================

# False path on SS_n to MISO: The slave does not drive MISO until SS_n is
# asserted and the first SCLK edge has occurred, so there is no direct
# timing relationship between the assertion of SS_n and the arrival of MISO.

# set_false_path -from [get_ports $SS_N_PORT] -to [get_ports $MISO_PORT]

# False path for SPI configuration/control registers that are written by
# software and are static during an SPI transaction (e.g., clock divider,
# SPI mode select, slave select register).
# Uncomment and adjust register paths to match your design hierarchy.

# set_false_path -from [get_registers ${SPI_MASTER_INST}|control_reg*]
# set_false_path -from [get_registers ${SPI_MASTER_INST}|bauddiv_reg*]
# set_false_path -from [get_registers ${SPI_MASTER_INST}|slaveselect_reg*]


# ==============================================================================
# Section 10: Multicycle Path Constraints
# ==============================================================================

# If the SPI SCLK is significantly slower than the system clock, the MOSI
# output and MISO input have multiple system clock cycles to settle. This
# can be expressed as a multicycle path to relax timing and avoid over-
# constraining the design.
#
# The multicycle factor is the ratio of system clock to SPI clock.
# For setup: data has N system clock cycles to propagate.
# For hold : use (N-1) to keep the hold check at the correct edge.

if {$sclk_div_factor > 1} {
    # MOSI output multicycle -- relax setup by the clock division factor
    set_multicycle_path -setup -end $sclk_div_factor \
        -to [get_ports $MOSI_PORT]
    set_multicycle_path -hold  -end [expr {$sclk_div_factor - 1}] \
        -to [get_ports $MOSI_PORT]

    # MISO input multicycle -- relax setup by the clock division factor
    set_multicycle_path -setup -end $sclk_div_factor \
        -from [get_ports $MISO_PORT]
    set_multicycle_path -hold  -end [expr {$sclk_div_factor - 1}] \
        -from [get_ports $MISO_PORT]

    # SS_n output multicycle
    set_multicycle_path -setup -end $sclk_div_factor \
        -to [get_ports $SS_N_PORT]
    set_multicycle_path -hold  -end [expr {$sclk_div_factor - 1}] \
        -to [get_ports $SS_N_PORT]
}


# ==============================================================================
# Section 11: Clock Uncertainty
# ==============================================================================

# Clock uncertainty accounts for jitter, skew, and other imprecisions in the
# clock network. The value should include:
#   - PLL output jitter (if SCLK is derived from a PLL)
#   - Board-level clock skew between SCLK and data lines
#   - Intra-die clock skew within the FPGA

# Setup uncertainty (pessimistic - tightens setup margin)
set_clock_uncertainty -setup 0.2 [get_clocks spi_sclk_out]

# Hold uncertainty (pessimistic - tightens hold margin)
set_clock_uncertainty -hold  0.1 [get_clocks spi_sclk_out]

# Apply uncertainty to the virtual clock as well
set_clock_uncertainty -setup 0.2 [get_clocks spi_sclk_virtual]
set_clock_uncertainty -hold  0.1 [get_clocks spi_sclk_virtual]


# ==============================================================================
# Section 12: I/O Standards and Drive Strength
# ==============================================================================

# Set the I/O standard for SPI pins. Common choices for 3.3V SPI:
#   LVCMOS33, LVTTL
# For 1.8V SPI:
#   LVCMOS18
# Adjust to match your bank voltage and slave device requirements.

# set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to $SCLK_PORT
# set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to $MOSI_PORT
# set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to $MISO_PORT
# set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to $SS_N_PORT

# Set output current strength for output pins (4mA, 8mA, 12mA, etc.)
# Higher drive strength reduces rise/fall times but increases noise/EMI.

# set_instance_assignment -name CURRENT_STRENGTH_NEW "8MA" -to $SCLK_PORT
# set_instance_assignment -name CURRENT_STRENGTH_NEW "8MA" -to $MOSI_PORT
# set_instance_assignment -name CURRENT_STRENGTH_NEW "8MA" -to $SS_N_PORT

# Slew rate control for output pins
# FAST slew rate for high-speed SPI, SLOW for reduced EMI.

# set_instance_assignment -name SLEW_RATE 1 -to $SCLK_PORT
# set_instance_assignment -name SLEW_RATE 1 -to $MOSI_PORT
# set_instance_assignment -name SLEW_RATE 1 -to $SS_N_PORT


# ==============================================================================
# End of SPI Master SDC Constraints
# ==============================================================================
