# ==============================================================================
# Altera SPI IP Core — Master Mode Timing Constraints
# ==============================================================================
#
# Target IP    : altera_avalon_spi (Intel/Altera Embedded Peripherals)
# Interface    : SPI Master
# SDC Version  : Synopsys Design Constraints (IEEE 1735 / Quartus Prime)
#
# This file constrains the four external SPI signals when the FPGA acts as the
# SPI bus master:
#
#   SCLK  — Serial Clock        (output, generated by FPGA)
#   MOSI  — Master Out Slave In (output, driven by FPGA)
#   MISO  — Master In Slave Out (input,  driven by external slave)
#   SS_n  — Slave Select         (output, active-low, driven by FPGA)
#
# Constraints are parameterised so they can be reused across designs by
# changing the variables at the top of the file.
#
# ==============================================================================

# ==============================================================================
# Section 1 — User-Configurable Parameters
# ==============================================================================
#
# Adjust these values to match your board-level design.
#
# SPI_CLK_FREQ_MHZ  : The SPI serial clock frequency in MHz.
# SYS_CLK_FREQ_MHZ  : The system (Avalon) clock frequency driving the IP core.
#
# Board propagation delays (nanoseconds, one-way):
#   BOARD_DELAY_MAX  : Maximum PCB trace + connector propagation delay.
#   BOARD_DELAY_MIN  : Minimum PCB trace + connector propagation delay.
#
# External slave device timing (from slave datasheet):
#   SLAVE_TSU        : Slave setup time  — how early data must be stable
#                      before the slave's sampling clock edge.
#   SLAVE_TH         : Slave hold time   — how long data must remain stable
#                      after the slave's sampling clock edge.
#   SLAVE_TCO_MAX    : Slave clock-to-output max — worst-case time from
#                      SCLK edge to valid MISO data at the slave pin.
#   SLAVE_TCO_MIN    : Slave clock-to-output min — best-case time from
#                      SCLK edge to valid MISO data at the slave pin.
# ==============================================================================

set SPI_CLK_FREQ_MHZ     25.0
set SYS_CLK_FREQ_MHZ    100.0

set BOARD_DELAY_MAX        1.5
set BOARD_DELAY_MIN        0.2

set SLAVE_TSU              5.0
set SLAVE_TH               2.0
set SLAVE_TCO_MAX          8.0
set SLAVE_TCO_MIN          1.0

# Derived periods (ns)
set SPI_CLK_PERIOD   [expr {1000.0 / $SPI_CLK_FREQ_MHZ}]
set SYS_CLK_PERIOD   [expr {1000.0 / $SYS_CLK_FREQ_MHZ}]


# ==============================================================================
# Section 2 — System Clock Definition
# ==============================================================================
#
# The system clock is the Avalon-MM clock that drives the SPI IP core
# internally. It must already be defined elsewhere (e.g., by the PLL IP or a
# top-level create_clock). If not, uncomment the line below.
#
# The SPI IP core uses this clock to serialise / deserialise data and to
# generate SCLK by dividing it down.
# ==============================================================================

# create_clock -name sys_clk -period $SYS_CLK_PERIOD [get_ports clk]


# ==============================================================================
# Section 3 — SPI Output Clock (SCLK) Definition
# ==============================================================================
#
# SCLK is generated internally by the SPI master IP through a clock divider
# from sys_clk.  We model it with create_generated_clock so the timing
# analyser knows the frequency and phase relationship.
#
# The -divide_by factor equals SYS_CLK_FREQ / SPI_CLK_FREQ.  For 100 MHz
# system clock and 25 MHz SPI clock this is 4.
#
# The -source should point to the register or PLL output that feeds the
# divider chain.  Update the path to match your synthesis hierarchy.
#
# We also define a virtual clock (spi_sclk_virtual) that represents the
# SCLK as seen at the external slave device.  Virtual clocks have no
# physical source in the FPGA but let us apply set_input_delay and
# set_output_delay relative to the clock the slave actually uses.
# ==============================================================================

set CLK_DIVIDE_FACTOR [expr {int($SYS_CLK_FREQ_MHZ / $SPI_CLK_FREQ_MHZ)}]

create_generated_clock \
    -name spi_sclk \
    -source [get_pins {spi_master|sclk_reg|clk}] \
    -divide_by $CLK_DIVIDE_FACTOR \
    [get_ports SPI_SCLK]

create_clock -name spi_sclk_virtual -period $SPI_CLK_PERIOD


# ==============================================================================
# Section 4 — Output Constraints: MOSI and SS_n
# ==============================================================================
#
# MOSI and SS_n are outputs from the FPGA master that are captured by the
# external slave on a specific SCLK edge.  The slave requires data to be
# stable for SLAVE_TSU before and SLAVE_TH after its sampling edge.
#
# In SPI Mode 0 (CPOL=0, CPHA=0) and Mode 3 (CPOL=1, CPHA=1) the slave
# samples MOSI on the rising edge of SCLK.
#
# In SPI Mode 1 (CPOL=0, CPHA=1) and Mode 2 (CPOL=1, CPHA=0) the slave
# samples MOSI on the falling edge of SCLK.
#
# The output delay values account for:
#   - Board propagation delay (FPGA pin → slave pin)
#   - Slave setup / hold requirements
#
# Formula:
#   set_output_delay -max = BOARD_DELAY_MAX + SLAVE_TSU
#   set_output_delay -min = -(SLAVE_TH - BOARD_DELAY_MIN)
#       (Negative min means the slave allows data to change that much
#        *before* hold time expires, once propagation delay is subtracted.)
#
# NOTE: If your design supports multiple SPI modes, include constraints for
# both edges and use set_false_path to disable the inactive edge analysis
# based on the mode your design is configured for.
# ==============================================================================

set MOSI_OUTPUT_DELAY_MAX [expr {$BOARD_DELAY_MAX + $SLAVE_TSU}]
set MOSI_OUTPUT_DELAY_MIN [expr {-($SLAVE_TH - $BOARD_DELAY_MIN)}]

# --- SPI Mode 0 / Mode 3: Slave samples on RISING edge of SCLK ---
set_output_delay -clock spi_sclk_virtual \
    -max $MOSI_OUTPUT_DELAY_MAX \
    [get_ports SPI_MOSI]

set_output_delay -clock spi_sclk_virtual \
    -min $MOSI_OUTPUT_DELAY_MIN \
    [get_ports SPI_MOSI]

# --- SPI Mode 1 / Mode 2: Slave samples on FALLING edge of SCLK ---
# Uncomment the following and comment out the block above if using Mode 1/2.
#
# set_output_delay -clock spi_sclk_virtual \
#     -max $MOSI_OUTPUT_DELAY_MAX \
#     -clock_fall \
#     [get_ports SPI_MOSI]
#
# set_output_delay -clock spi_sclk_virtual \
#     -min $MOSI_OUTPUT_DELAY_MIN \
#     -clock_fall \
#     [get_ports SPI_MOSI]

# Slave Select (active-low chip select) — same timing relationship as MOSI
# since the slave latches SS_n relative to SCLK.  In practice SS_n toggles
# well before the first SCLK edge, so setup/hold are easily met.  We still
# constrain it for completeness.

set_output_delay -clock spi_sclk_virtual \
    -max $MOSI_OUTPUT_DELAY_MAX \
    [get_ports SPI_SS_n]

set_output_delay -clock spi_sclk_virtual \
    -min $MOSI_OUTPUT_DELAY_MIN \
    [get_ports SPI_SS_n]


# ==============================================================================
# Section 5 — Input Constraints: MISO
# ==============================================================================
#
# MISO is driven by the external slave and captured inside the FPGA by the
# SPI master IP.  The FPGA samples MISO on the opposite SCLK edge from the
# one on which the slave drives data.
#
# In SPI Mode 0 / Mode 3 the slave shifts data out on the FALLING edge
# and the master samples on the RISING edge.
#
# In SPI Mode 1 / Mode 2 the slave shifts data out on the RISING edge
# and the master samples on the FALLING edge.
#
# For set_input_delay the reference is the *launch* clock edge (the edge at
# which the slave drives MISO).  Quartus models the full round-trip:
#
#   FPGA launches SCLK → board delay → SCLK arrives at slave →
#   slave clock-to-output (TCO) → board delay back → MISO arrives at FPGA.
#
# Formula:
#   set_input_delay -max = BOARD_DELAY_MAX (SCLK out) + SLAVE_TCO_MAX
#                          + BOARD_DELAY_MAX (MISO return)
#   set_input_delay -min = BOARD_DELAY_MIN (SCLK out) + SLAVE_TCO_MIN
#                          + BOARD_DELAY_MIN (MISO return)
#
# The round-trip board delay is counted twice (once for SCLK going out,
# once for MISO coming back).
# ==============================================================================

set MISO_INPUT_DELAY_MAX [expr {2 * $BOARD_DELAY_MAX + $SLAVE_TCO_MAX}]
set MISO_INPUT_DELAY_MIN [expr {2 * $BOARD_DELAY_MIN + $SLAVE_TCO_MIN}]

# --- SPI Mode 0 / Mode 3: Master samples on RISING, slave shifts on FALLING ---
set_input_delay -clock spi_sclk_virtual \
    -max $MISO_INPUT_DELAY_MAX \
    -clock_fall \
    [get_ports SPI_MISO]

set_input_delay -clock spi_sclk_virtual \
    -min $MISO_INPUT_DELAY_MIN \
    -clock_fall \
    [get_ports SPI_MISO]

# --- SPI Mode 1 / Mode 2: Master samples on FALLING, slave shifts on RISING ---
# Uncomment the following and comment out the block above if using Mode 1/2.
#
# set_input_delay -clock spi_sclk_virtual \
#     -max $MISO_INPUT_DELAY_MAX \
#     [get_ports SPI_MISO]
#
# set_input_delay -clock spi_sclk_virtual \
#     -min $MISO_INPUT_DELAY_MIN \
#     [get_ports SPI_MISO]


# ==============================================================================
# Section 6 — Clock Uncertainty (Jitter)
# ==============================================================================
#
# Clock uncertainty accounts for jitter on both the system clock and the
# generated SCLK, plus any PLL uncertainty.  Quartus can derive this
# automatically from PLL parameters, but an explicit value gives tighter
# control.
#
# The value below is a conservative starting point; refine it using your
# PLL or oscillator datasheet.
# ==============================================================================

set_clock_uncertainty -setup 0.200 [get_clocks spi_sclk]
set_clock_uncertainty -hold  0.050 [get_clocks spi_sclk]

set_clock_uncertainty -setup 0.200 [get_clocks spi_sclk_virtual]
set_clock_uncertainty -hold  0.050 [get_clocks spi_sclk_virtual]


# ==============================================================================
# Section 7 — Clock Group Separation / False Paths
# ==============================================================================
#
# The SPI clock domain and the system clock domain are related (SCLK is
# derived from sys_clk), so Quartus can analyse paths between them
# automatically.
#
# However, certain paths are logically impossible and should be excluded
# to prevent false timing violations:
#
#   1. There is no combinational path from MISO input directly to any
#      output; data always passes through at least one register.
#   2. SS_n is asserted/de-asserted asynchronously with respect to SCLK
#      toggling; it is a quasi-static signal during transfers.
#
# If SCLK is NOT generated from sys_clk (e.g., external oscillator), you
# must declare them as asynchronous clock groups:
#
#   set_clock_groups -asynchronous \
#       -group [get_clocks sys_clk] \
#       -group [get_clocks spi_sclk_virtual]
# ==============================================================================

# False path: no direct MISO → MOSI combinational feed-through
set_false_path -from [get_ports SPI_MISO] -to [get_ports SPI_MOSI]
set_false_path -from [get_ports SPI_MISO] -to [get_ports SPI_SS_n]
set_false_path -from [get_ports SPI_MISO] -to [get_ports SPI_SCLK]


# ==============================================================================
# Section 8 — Multicycle Path Constraints
# ==============================================================================
#
# If the SPI IP core uses a clock-enable architecture (common when SCLK is
# much slower than sys_clk), the internal data path between the Avalon
# register file and the SPI shift register may only transfer data once
# every N sys_clk cycles (where N = CLK_DIVIDE_FACTOR).
#
# Declaring a multicycle path relaxes the setup requirement from one
# sys_clk period to N sys_clk periods, giving the tool more room and
# avoiding unnecessary over-constraining.
#
# Apply this ONLY if you can confirm the IP core uses a clock-enable
# structure.  The altera_avalon_spi core typically does.
# ==============================================================================

# Multicycle setup: allow N system clock periods for data transfer
# between Avalon domain and SPI shift register.
# set_multicycle_path -setup $CLK_DIVIDE_FACTOR \
#     -from [get_clocks sys_clk] \
#     -to   [get_clocks spi_sclk]
#
# Multicycle hold: standard companion to multicycle setup.
# set_multicycle_path -hold [expr {$CLK_DIVIDE_FACTOR - 1}] \
#     -from [get_clocks sys_clk] \
#     -to   [get_clocks spi_sclk]


# ==============================================================================
# Section 9 — I/O Timing Exceptions and Min/Max Analysis
# ==============================================================================
#
# Quartus performs both "slow" (max/setup) and "fast" (min/hold) timing
# analysis.  The constraints above already supply -max and -min values, so
# both analyses are covered.
#
# If your design targets multiple speed grades or temperature corners, you
# may wish to run the TimeQuest Timing Analyzer in both "slow 85C" and
# "fast 0C" models.  The SDC file does not need to change; the .qsf
# setting controls which model is used:
#
#   set_global_assignment -name TIMING_ANALYZER_MULTICORNER_ANALYSIS ON
# ==============================================================================


# ==============================================================================
# Section 10 — Port-Level I/O Standard Constraints
# ==============================================================================
#
# While not strictly SDC, specifying the I/O standard ensures the timing
# model uses correct buffer delays.  Typical SPI interfaces use 3.3 V
# LVCMOS or 2.5 V LVCMOS.  Set these in the .qsf or via SDC:
#
#   set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" \
#       -to SPI_SCLK
#   set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" \
#       -to SPI_MOSI
#   set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" \
#       -to SPI_MISO
#   set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" \
#       -to SPI_SS_n
#
# These are QSF assignments, not SDC commands, but are included here for
# reference.
# ==============================================================================

# ==============================================================================
# End of SPI Master Timing Constraints
# ==============================================================================
