# ==============================================================================
# SDC Timing Constraints for Altera (Intel) SPI Master IP
# ==============================================================================
#
# Target Device  : Intel (Altera) FPGA (Cyclone / Arria / Stratix families)
# IP             : Altera SPI Master Core (ALTSERIAL_SPI / Intel SPI Master)
# Tool           : Quartus Prime (Standard / Pro Edition)
#
# Description    : This SDC file defines the complete set of timing constraints
#                  required for correct static timing analysis of an SPI master
#                  controller implemented in an Intel FPGA. The SPI master
#                  generates the serial clock (SCLK), drives MOSI, samples MISO,
#                  and asserts chip-select (SS_n).
#
# SPI Protocol   : Supports all four SPI modes (0-3) via CPOL/CPHA settings.
#                  The constraints below assume worst-case launch/capture edges.
#
# Revision       : 1.0
# ==============================================================================


# ==============================================================================
#  Section 1 : User-Configurable Parameters
# ==============================================================================
# Adjust these values to match your design. All times are in nanoseconds (ns),
# all frequencies in megahertz (MHz).

# System clock frequency driving the SPI master logic
set SYS_CLK_FREQ_MHZ       100.0

# SPI serial clock (SCLK) frequency — must be an integer divisor of SYS_CLK
set SPI_CLK_FREQ_MHZ       25.0

# Board-level trace / flight-time delays (PCB routing delays in ns)
set BOARD_DELAY_MAX         1.5
set BOARD_DELAY_MIN         0.5

# SPI slave device timing (from the slave datasheet)
set SLAVE_TCO_MAX           8.0   ;# Slave clock-to-output (MISO) max
set SLAVE_TCO_MIN           2.0   ;# Slave clock-to-output (MISO) min
set SLAVE_TSU              5.0   ;# Slave setup time for MOSI
set SLAVE_TH               2.0   ;# Slave hold time for MOSI

# FPGA I/O buffer delays (obtained from Quartus Timing Analyzer or datasheet)
set FPGA_OUT_DELAY_MAX      3.0   ;# FPGA output buffer delay max
set FPGA_OUT_DELAY_MIN      1.0   ;# FPGA output buffer delay min
set FPGA_IN_DELAY_MAX       2.5   ;# FPGA input buffer delay max
set FPGA_IN_DELAY_MIN       0.8   ;# FPGA input buffer delay min

# Pin names — update these to match your Quartus pin assignments
set PIN_SCLK                "spi_sclk"
set PIN_MOSI                "spi_mosi"
set PIN_MISO                "spi_miso"
set PIN_SS_N                "spi_ss_n"
set SYS_CLK_PIN             "sys_clk"


# ==============================================================================
#  Section 2 : System Clock Definition
# ==============================================================================
# Define the primary system clock that feeds the SPI master logic.
# This clock drives the clock divider that generates the SPI serial clock.

set SYS_CLK_PERIOD [expr {1000.0 / $SYS_CLK_FREQ_MHZ}]

create_clock -name sys_clk \
             -period $SYS_CLK_PERIOD \
             [get_ports $SYS_CLK_PIN]


# ==============================================================================
#  Section 3 : SPI Serial Clock (SCLK) — Generated Clock
# ==============================================================================
# The SPI master internally divides the system clock to produce SCLK.
# We model SCLK as a generated clock sourced from the system clock.
# The division factor is SYS_CLK_FREQ / SPI_CLK_FREQ.

set SPI_CLK_PERIOD  [expr {1000.0 / $SPI_CLK_FREQ_MHZ}]
set CLK_DIV_FACTOR  [expr {int($SYS_CLK_FREQ_MHZ / $SPI_CLK_FREQ_MHZ)}]

create_generated_clock -name spi_sclk \
                       -source [get_ports $SYS_CLK_PIN] \
                       -divide_by $CLK_DIV_FACTOR \
                       [get_ports $PIN_SCLK]

# Alternatively, if SCLK is generated by a register inside the SPI IP core,
# trace the register path and use:
#
# create_generated_clock -name spi_sclk \
#     -source [get_pins {spi_master_inst|sclk_reg|clk}] \
#     -divide_by $CLK_DIV_FACTOR \
#     [get_ports $PIN_SCLK]


# ==============================================================================
#  Section 4 : Output Delay Constraints — MOSI and SS_n
# ==============================================================================
# MOSI and SS_n are driven by the SPI master and captured by the slave device.
# The slave samples MOSI on the appropriate SCLK edge based on SPI mode.
#
# Output delay = board trace delay + slave setup/hold requirements
#
# set_output_delay -max : accounts for longest path (worst-case late arrival)
# set_output_delay -min : accounts for shortest path (worst-case early arrival)
#
# The -clock reference is spi_sclk because the slave captures data relative
# to the SPI clock edge.

# --- Maximum output delay (setup analysis) ---
# Data must arrive at the slave at least TSU before the capturing SCLK edge.
# max output delay = board_delay_max + slave_setup
set MOSI_OUTPUT_DELAY_MAX [expr {$BOARD_DELAY_MAX + $SLAVE_TSU}]

# --- Minimum output delay (hold analysis) ---
# Data must be held stable for at least TH after the capturing SCLK edge.
# min output delay = board_delay_min  (negative hold margin handled internally)
set MOSI_OUTPUT_DELAY_MIN [expr {$BOARD_DELAY_MIN}]

# MOSI output delay constraints
set_output_delay -clock spi_sclk \
                 -max $MOSI_OUTPUT_DELAY_MAX \
                 [get_ports $PIN_MOSI]

set_output_delay -clock spi_sclk \
                 -min $MOSI_OUTPUT_DELAY_MIN \
                 [get_ports $PIN_MOSI]

# SS_n (chip select, directly managed by the master, active-low)
# SS_n must be asserted well before the first SCLK edge and deasserted after
# the last edge. The same output delay model applies.
set_output_delay -clock spi_sclk \
                 -max $MOSI_OUTPUT_DELAY_MAX \
                 [get_ports $PIN_SS_N]

set_output_delay -clock spi_sclk \
                 -min $MOSI_OUTPUT_DELAY_MIN \
                 [get_ports $PIN_SS_N]


# ==============================================================================
#  Section 5 : Input Delay Constraints — MISO
# ==============================================================================
# MISO is driven by the slave and sampled by the SPI master on the returning
# SCLK edge (or a delayed internal version of SCLK).
#
# Input delay = slave TCO + board trace delay
#
# The -clock reference is spi_sclk. The master captures MISO on the opposite
# edge from the one that launched data on MOSI (depends on CPOL/CPHA).
#
# Use -clock_fall if the master samples on the falling edge of SCLK.

# --- Maximum input delay (setup analysis) ---
# max input delay = slave_tco_max + board_delay_max
set MISO_INPUT_DELAY_MAX [expr {$SLAVE_TCO_MAX + $BOARD_DELAY_MAX}]

# --- Minimum input delay (hold analysis) ---
# min input delay = slave_tco_min + board_delay_min
set MISO_INPUT_DELAY_MIN [expr {$SLAVE_TCO_MIN + $BOARD_DELAY_MIN}]

set_input_delay -clock spi_sclk \
                -max $MISO_INPUT_DELAY_MAX \
                [get_ports $PIN_MISO]

set_input_delay -clock spi_sclk \
                -min $MISO_INPUT_DELAY_MIN \
                [get_ports $PIN_MISO]

# For SPI Mode 0 or Mode 3 (CPHA=0), the master samples MISO on the rising
# edge while launching MOSI on the falling edge — or vice versa. If sampling
# occurs on the falling edge, add -clock_fall:
#
# set_input_delay -clock spi_sclk -clock_fall \
#                 -max $MISO_INPUT_DELAY_MAX \
#                 [get_ports $PIN_MISO]
#
# set_input_delay -clock spi_sclk -clock_fall \
#                 -min $MISO_INPUT_DELAY_MIN \
#                 [get_ports $PIN_MISO]


# ==============================================================================
#  Section 6 : Clock Groups — Asynchronous Clock Domains
# ==============================================================================
# If the SPI clock and the system clock are treated as asynchronous (e.g., the
# SPI master uses a FIFO or handshake for domain crossing), declare them as
# exclusive or asynchronous clock groups to prevent false cross-domain paths.
#
# Use -asynchronous if the clocks are truly unrelated.
# Use -exclusive if they share a common source but never coexist.

# set_clock_groups -asynchronous \
#     -group [get_clocks sys_clk] \
#     -group [get_clocks spi_sclk]

# Since spi_sclk is derived from sys_clk, the clocks are synchronous and the
# above is commented out by default. Uncomment ONLY if your design inserts an
# asynchronous boundary (e.g., dual-clock FIFO) between the domains.


# ==============================================================================
#  Section 7 : Multicycle Path Constraints
# ==============================================================================
# The SPI master often registers MISO data through multiple pipeline stages
# before it is consumed by the system-clock domain. If such pipelining exists,
# relax the timing with multicycle path constraints.
#
# Example: 2-stage synchronizer on the MISO capture path
# The setup check is relaxed by 1 additional cycle (total of 2 sys_clk cycles).

# set_multicycle_path -setup 2 \
#     -from [get_clocks spi_sclk] \
#     -to   [get_clocks sys_clk]
#
# set_multicycle_path -hold 1 \
#     -from [get_clocks spi_sclk] \
#     -to   [get_clocks sys_clk]


# ==============================================================================
#  Section 8 : False Path Constraints
# ==============================================================================
# Certain paths in the SPI master do not require timing analysis because they
# are either static configuration signals or reset paths.

# SS_n assertion/deassertion is typically managed by firmware and does not have
# a cycle-accurate timing requirement relative to SCLK data edges, so it can
# be treated as a false path in some designs. Use with caution — only apply
# if your design truly does not require timing on this path.

# set_false_path -from [get_registers {*spi_master*|ss_n_reg*}] \
#                -to   [get_ports $PIN_SS_N]

# Asynchronous reset — if the SPI master has an asynchronous reset input,
# declare it as a false path so the timing analyzer does not attempt to
# analyze timing on the reset deassertion path.

# set_false_path -from [get_ports reset_n]


# ==============================================================================
#  Section 9 : Maximum Skew / Delay Constraints (Optional)
# ==============================================================================
# Constrain the maximum skew between SPI bus signals to ensure simultaneous
# arrival at the slave device. This is important at high SPI clock rates.

# set_max_skew -from [get_ports $PIN_SCLK] \
#              -to   [get_ports "$PIN_MOSI $PIN_SS_N"] \
#              0.5

# Constrain the maximum net delay on the SPI clock output to control
# clock-to-output jitter seen by the slave.
# set_max_delay -from [get_registers {*spi_master*|sclk_reg}] \
#               -to   [get_ports $PIN_SCLK] \
#               5.0


# ==============================================================================
#  Section 10 : I/O Timing Exceptions and Overrides
# ==============================================================================
# If specific SPI transfers use a slower clock rate (e.g., during
# initialization), you can apply per-mode constraints using set_case_analysis
# or mode-specific SDC files loaded conditionally.

# Example: Force CPOL=0 for timing analysis
# set_case_analysis 0 [get_registers {*spi_master*|cpol_reg}]

# Example: Apply different constraints for a secondary SPI clock rate
# create_generated_clock -name spi_sclk_slow \
#     -source [get_ports $SYS_CLK_PIN] \
#     -divide_by [expr {$CLK_DIV_FACTOR * 4}] \
#     -add \
#     [get_ports $PIN_SCLK]


# ==============================================================================
#  Section 11 : Report Aliases (Convenience)
# ==============================================================================
# Create meaningful aliases for the TimeQuest / Timing Analyzer reports
# to make the constraint coverage report easier to read.

set_clock_uncertainty -setup 0.1 [get_clocks spi_sclk]
set_clock_uncertainty -hold  0.05 [get_clocks spi_sclk]


# ==============================================================================
#  End of SPI Master SDC Constraints
# ==============================================================================
