# ==============================================================================
# SDC Constraints for Altera (Intel) SPI Master IP Core
# ==============================================================================
#
# Description:
#   Timing constraints for the Altera/Intel FPGA SPI Master peripheral IP.
#   The SPI Master drives SCLK, MOSI, and SS_n (active-low slave select)
#   as outputs, and samples MISO as an input.
#
# SPI Signal Summary (Master perspective):
#   SCLK  - Serial Clock       (output, generated by the master)
#   MOSI  - Master Out Slave In (output, data driven by the master)
#   MISO  - Master In Slave Out (input,  data driven by the slave)
#   SS_n  - Slave Select        (output, directly controlled by the master)
#
# SPI Modes (CPOL/CPHA):
#   Mode 0 (CPOL=0, CPHA=0): SCLK idles low,  data sampled on rising  edge
#   Mode 1 (CPOL=0, CPHA=1): SCLK idles low,  data sampled on falling edge
#   Mode 2 (CPOL=1, CPHA=0): SCLK idles high, data sampled on rising  edge
#   Mode 3 (CPOL=1, CPHA=1): SCLK idles high, data sampled on falling edge
#
# Usage:
#   1. Adjust the parameter section below to match your design.
#   2. Update pin/port/instance names to match your Quartus project hierarchy.
#   3. Source this file in Quartus via: Project > Settings > Timing Analyzer
#      > SDC files, or include it in your project's .qsf file.
#
# Target Tool: Intel Quartus Prime Timing Analyzer (TimeQuest)
# ==============================================================================


# ==============================================================================
# Section 1: Design Parameters -- Adjust these to match your design
# ==============================================================================

# System clock frequency (Hz) feeding the SPI Master IP core
set SYS_CLK_FREQ_MHZ       50.0
set SYS_CLK_PERIOD_NS      [expr {1000.0 / $SYS_CLK_FREQ_MHZ}]

# SPI serial clock frequency (Hz) -- this is SCLK on the bus
# Typically the system clock divided by an even integer (2, 4, 8, ...)
set SPI_CLK_FREQ_MHZ       12.5
set SPI_CLK_PERIOD_NS      [expr {1000.0 / $SPI_CLK_FREQ_MHZ}]

# Clock division factor: SYS_CLK / SCLK
set SPI_CLK_DIV             [expr {int($SYS_CLK_FREQ_MHZ / $SPI_CLK_FREQ_MHZ)}]

# Board-level trace delays (nanoseconds) -- measure or estimate from PCB layout
set BOARD_DELAY_MAX         1.5   ;# Maximum PCB trace propagation delay
set BOARD_DELAY_MIN         0.5   ;# Minimum PCB trace propagation delay

# SPI Slave device timing parameters (from slave device datasheet)
# These represent the external slave's setup/hold and clock-to-output specs
set SLAVE_TSU               5.0   ;# Slave setup time for MOSI (before SCLK edge)
set SLAVE_TH                2.0   ;# Slave hold time for MOSI (after SCLK edge)
set SLAVE_TCO_MAX           8.0   ;# Slave max clock-to-output for MISO
set SLAVE_TCO_MIN           1.0   ;# Slave min clock-to-output for MISO
set SLAVE_TSS_SU            5.0   ;# Slave select setup time (SS_n active before first SCLK)
set SLAVE_TSS_HD            5.0   ;# Slave select hold time (SS_n held after last SCLK)

# Quartus hierarchy path to the SPI master IP instance
# Update this to match your design hierarchy
set SPI_MASTER_INST         "u_spi_master"


# ==============================================================================
# Section 2: System (Reference) Clock Definition
# ==============================================================================

# Define the primary system clock that drives the SPI master IP.
# This clock feeds the Avalon-MM bus interface and internal logic.
create_clock \
    -name sys_clk \
    -period $SYS_CLK_PERIOD_NS \
    [get_ports clk]


# ==============================================================================
# Section 3: SPI Generated Clock (SCLK)
# ==============================================================================

# SCLK is generated internally by the SPI master from the system clock via a
# clock divider. It is a generated clock whose frequency = sys_clk / SPI_CLK_DIV.
# The master_clk flag tells TimeQuest about the parent-child relationship.
#
# The -source points to the system clock port; the -divide_by sets the ratio.
# Adjust the -source if your SCLK is driven from a PLL output instead.

create_generated_clock \
    -name spi_sclk \
    -source [get_ports clk] \
    -divide_by $SPI_CLK_DIV \
    [get_ports spi_clk]


# ==============================================================================
# Section 4: Clock Uncertainty and Jitter
# ==============================================================================

# Clock uncertainty accounts for PLL jitter, board-level clock skew, and
# intra-die variation. Apply to both the system clock and the generated SCLK.
#
# -setup: Additional pessimism for setup analysis (makes timing harder to meet)
# -hold:  Additional pessimism for hold analysis

set_clock_uncertainty -setup 0.2 [get_clocks sys_clk]
set_clock_uncertainty -hold  0.1 [get_clocks sys_clk]

set_clock_uncertainty -setup 0.3 [get_clocks spi_sclk]
set_clock_uncertainty -hold  0.1 [get_clocks spi_sclk]


# ==============================================================================
# Section 5: MISO Input Constraints (Data FROM the slave device)
# ==============================================================================

# The slave drives MISO relative to the SCLK edge it receives. The FPGA master
# samples MISO on the opposite SCLK edge (half a period later).
#
# Input delay = board delay + slave clock-to-output time
#
# set_input_delay -max: longest time from SCLK edge to valid MISO at FPGA pin
# set_input_delay -min: shortest time from SCLK edge to valid MISO at FPGA pin
#
# The -clock_fall flag is used when the slave launches data on the falling edge
# of SCLK (SPI Mode 0 / Mode 3). Remove -clock_fall for Mode 1 / Mode 2.

# --- Maximum input delay (for setup analysis) ---
set_input_delay \
    -clock spi_sclk \
    -max [expr {$BOARD_DELAY_MAX + $SLAVE_TCO_MAX}] \
    [get_ports spi_miso]

# --- Minimum input delay (for hold analysis) ---
set_input_delay \
    -clock spi_sclk \
    -min [expr {$BOARD_DELAY_MIN + $SLAVE_TCO_MIN}] \
    [get_ports spi_miso]

# If your design uses SPI Mode 0 or Mode 3 where the slave launches data on
# the falling SCLK edge and the master captures on rising, add -clock_fall:
#
# set_input_delay -clock spi_sclk -clock_fall \
#     -max [expr {$BOARD_DELAY_MAX + $SLAVE_TCO_MAX}] \
#     [get_ports spi_miso]
#
# set_input_delay -clock spi_sclk -clock_fall \
#     -min [expr {$BOARD_DELAY_MIN + $SLAVE_TCO_MIN}] \
#     [get_ports spi_miso]


# ==============================================================================
# Section 6: MOSI Output Constraints (Data TO the slave device)
# ==============================================================================

# The master drives MOSI and the slave samples it relative to SCLK.
# Output delay is specified from the SCLK edge perspective at the slave.
#
# set_output_delay -max = board_delay + slave_setup_time
#   (data must arrive at slave's input this long BEFORE the sampling SCLK edge)
#
# set_output_delay -min = -(board_delay_min - slave_hold_time)
#   (data must be held at slave's input this long AFTER the sampling SCLK edge;
#    negative value means hold must be met after the edge)

# --- Maximum output delay (for setup analysis at the slave) ---
set_output_delay \
    -clock spi_sclk \
    -max [expr {$BOARD_DELAY_MAX + $SLAVE_TSU}] \
    [get_ports spi_mosi]

# --- Minimum output delay (for hold analysis at the slave) ---
set_output_delay \
    -clock spi_sclk \
    -min [expr {$BOARD_DELAY_MIN - $SLAVE_TH}] \
    [get_ports spi_mosi]


# ==============================================================================
# Section 7: Slave Select (SS_n) Output Constraints
# ==============================================================================

# SS_n is asserted (driven low) before the first SCLK edge and deasserted
# (driven high) after the last SCLK edge. The slave requires a minimum setup
# and hold time relative to SCLK edges.
#
# Constrain SS_n similarly to MOSI to ensure the slave sees it with enough
# margin around SCLK transitions.

# --- Maximum output delay for SS_n ---
set_output_delay \
    -clock spi_sclk \
    -max [expr {$BOARD_DELAY_MAX + $SLAVE_TSS_SU}] \
    [get_ports spi_ss_n]

# --- Minimum output delay for SS_n ---
set_output_delay \
    -clock spi_sclk \
    -min [expr {$BOARD_DELAY_MIN - $SLAVE_TSS_HD}] \
    [get_ports spi_ss_n]

# If your design has multiple slave selects (active-low, active one at a time),
# apply to all SS_n ports, e.g.:
#
# set_output_delay -clock spi_sclk \
#     -max [expr {$BOARD_DELAY_MAX + $SLAVE_TSS_SU}] \
#     [get_ports {spi_ss_n[*]}]
#
# set_output_delay -clock spi_sclk \
#     -min [expr {$BOARD_DELAY_MIN - $SLAVE_TSS_HD}] \
#     [get_ports {spi_ss_n[*]}]


# ==============================================================================
# Section 8: SCLK Output Constraints
# ==============================================================================

# SCLK itself has output delay that accounts for the PCB trace to the slave.
# This ensures the Timing Analyzer models the actual clock arrival time at the
# slave device pins when analyzing MOSI/MISO timing.

set_output_delay \
    -clock spi_sclk \
    -max $BOARD_DELAY_MAX \
    [get_ports spi_clk]

set_output_delay \
    -clock spi_sclk \
    -min $BOARD_DELAY_MIN \
    [get_ports spi_clk]


# ==============================================================================
# Section 9: Multicycle Path Constraints
# ==============================================================================

# If the SPI clock divider ratio is large (e.g., sys_clk=100 MHz, SCLK=1 MHz),
# the internal logic may have multicycle paths between the system clock domain
# and the SPI clock domain. These constraints relax timing analysis so that
# TimeQuest does not over-constrain paths that have multiple system clock cycles
# to propagate.
#
# The setup multicycle = SPI_CLK_DIV means the data has SPI_CLK_DIV system
# clock edges to propagate. The hold multicycle = SPI_CLK_DIV - 1 adjusts the
# hold check to the correct reference edge.

if {$SPI_CLK_DIV > 1} {
    set_multicycle_path \
        -setup $SPI_CLK_DIV \
        -from [get_clocks sys_clk] \
        -to [get_clocks spi_sclk]

    set_multicycle_path \
        -hold [expr {$SPI_CLK_DIV - 1}] \
        -from [get_clocks sys_clk] \
        -to [get_clocks spi_sclk]

    set_multicycle_path \
        -setup $SPI_CLK_DIV \
        -from [get_clocks spi_sclk] \
        -to [get_clocks sys_clk]

    set_multicycle_path \
        -hold [expr {$SPI_CLK_DIV - 1}] \
        -from [get_clocks spi_sclk] \
        -to [get_clocks sys_clk]
}


# ==============================================================================
# Section 10: False Path Constraints
# ==============================================================================

# Reset and static configuration signals are asynchronous and should not be
# timed against the SPI clock domain. Mark them as false paths to prevent
# incorrect timing violations.

# Asynchronous reset (active-low) -- does not need to meet SPI clock timing
set_false_path -from [get_ports reset_n]

# If you have a directly active-high reset:
# set_false_path -from [get_ports reset]

# Static configuration registers (e.g., clock polarity, clock phase selection)
# that are written once at startup and never change during SPI transactions.
# These do not need to be timed against SCLK.
#
# set_false_path \
#     -from [get_registers ${SPI_MASTER_INST}|cpol_reg] \
#     -to [get_clocks spi_sclk]
#
# set_false_path \
#     -from [get_registers ${SPI_MASTER_INST}|cpha_reg] \
#     -to [get_clocks spi_sclk]

# If SCLK is completely asynchronous to another clock domain (e.g., a separate
# JTAG clock), add a false path between them:
#
# set_false_path -from [get_clocks spi_sclk] -to [get_clocks jtag_clk]
# set_false_path -from [get_clocks jtag_clk] -to [get_clocks spi_sclk]


# ==============================================================================
# Section 11: I/O Timing Exceptions and Advanced Constraints
# ==============================================================================

# If your design uses a PLL to generate the system clock, derive the PLL clocks
# automatically. This ensures all PLL output clocks are properly constrained.

derive_pll_clocks

# Derive clock uncertainty from jitter characteristics of PLLs and on-chip
# clock networks. This is Intel/Altera-specific and overrides manual
# set_clock_uncertainty for PLL-generated clocks.

derive_clock_uncertainty


# ==============================================================================
# Section 12: Output Maximum Skew Constraints (Optional)
# ==============================================================================

# For high-speed SPI (> 25 MHz), it may be necessary to control the skew
# between SCLK and MOSI/SS_n to ensure reliable data capture at the slave.
#
# set_max_skew -from [get_ports spi_clk] -to [get_ports spi_mosi] 0.5
# set_max_skew -from [get_ports spi_clk] -to [get_ports spi_ss_n] 0.5


# ==============================================================================
# Section 13: I/O Standard and Drive Strength (Informational)
# ==============================================================================

# These are typically set in the .qsf file but are noted here for completeness.
# Ensure your SPI I/O pins use the correct voltage standard:
#
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to spi_clk
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to spi_mosi
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to spi_miso
# set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to spi_ss_n
#
# set_instance_assignment -name CURRENT_STRENGTH_NEW "8mA" -to spi_clk
# set_instance_assignment -name CURRENT_STRENGTH_NEW "8mA" -to spi_mosi
# set_instance_assignment -name CURRENT_STRENGTH_NEW "8mA" -to spi_ss_n


# ==============================================================================
# End of Altera SPI Master SDC Constraints
# ==============================================================================
