#==============================================================
# UART Controller - SDC Constraints
#
# Demonstrates:
#   - Clock definition for system clock
#   - Asynchronous input handling (rx_in)
#   - Output constraints for tx_out
#   - False paths for async inputs and reset
#
# Design: UART TX + RX running at 115200 baud
# System Clock: 50 MHz
#==============================================================

#--------------------------------------------------------------
# Clock Definition
#--------------------------------------------------------------

create_clock -name sys_clk -period 20.000 [get_ports clk]
derive_clock_uncertainty

#--------------------------------------------------------------
# Input Constraints
#--------------------------------------------------------------

# TX data input (from internal logic, synchronous to sys_clk)
# Assume upstream register Tco = 5 ns, board delay = 1.5 ns
set_input_delay -clock sys_clk -max 6.500 [get_ports {tx_data[*]}]
set_input_delay -clock sys_clk -min 1.500 [get_ports {tx_data[*]}]

set_input_delay -clock sys_clk -max 6.500 [get_ports tx_valid]
set_input_delay -clock sys_clk -min 1.500 [get_ports tx_valid]

#--------------------------------------------------------------
# Output Constraints
#--------------------------------------------------------------

# UART TX output goes to an off-board connector
# Since UART is asynchronous, the constraint is mainly for
# ensuring the output register meets internal timing.
# We use a relaxed output delay since the UART protocol
# is self-clocking at the baud rate level.

set_output_delay -clock sys_clk -max 8.000 [get_ports tx_out]
set_output_delay -clock sys_clk -min 0.000 [get_ports tx_out]

set_output_delay -clock sys_clk -max 8.000 [get_ports tx_busy]
set_output_delay -clock sys_clk -min 0.000 [get_ports tx_busy]

#--------------------------------------------------------------
# UART RX Input - Asynchronous
#--------------------------------------------------------------

# The RX input is asynchronous (comes from an external UART
# transmitter). It is synchronized internally using a
# double-flop synchronizer (rx_sync_0, rx_sync_1).
# Therefore, we declare it as a false path.

set_false_path -from [get_ports rx_in]

# RX data output
set_output_delay -clock sys_clk -max 5.000 [get_ports {rx_data[*]}]
set_output_delay -clock sys_clk -min 0.000 [get_ports {rx_data[*]}]

set_output_delay -clock sys_clk -max 5.000 [get_ports rx_valid]
set_output_delay -clock sys_clk -min 0.000 [get_ports rx_valid]

#--------------------------------------------------------------
# Asynchronous Reset
#--------------------------------------------------------------

set_false_path -from [get_ports rst_n]

#--------------------------------------------------------------
# Notes on Baud Rate Generator
#--------------------------------------------------------------
# The baud rate is generated by counting system clock cycles.
# This does NOT create a new clock domain! The baud_tick signal
# is simply a clock enable -- all logic remains in the sys_clk
# domain. No generated clock or multicycle path is needed for
# the baud counter itself.
#
# If the design had a physical clock divider producing a baud
# clock on a register output, THEN you would need:
#
#   create_generated_clock -name baud_clk \
#       -source [get_ports clk] \
#       -divide_by 434 \
#       [get_registers baud_clk_reg]
#
# But our design uses a clock enable pattern, which is the
# preferred approach.
