#!/usr/bin/perl
use strict;
use warnings;
use feature 'say';
use File::Temp qw(tempdir);

# ============================================================
# File Writing Operations
# ============================================================

my $tmpdir = tempdir(CLEANUP => 1);
say "Working in temp directory: $tmpdir";

say "\n=== WRITE MODE (create/overwrite) ===";

my $outfile = "$tmpdir/output.txt";
open(my $fh, '>', $outfile) or die "Cannot open for writing: $!\n";

print $fh "Line 1: Hello, World!\n";
print $fh "Line 2: Writing to files in Perl\n";
print $fh "Line 3: This is straightforward\n";

close($fh);
say "Wrote 3 lines to $outfile";

open(my $verify, '<', $outfile) or die "Cannot read back: $!\n";
print "  $_" while <$verify>;
close($verify);

say "\n=== APPEND MODE ===";

open(my $append, '>>', $outfile) or die "Cannot open for append: $!\n";
print $append "Line 4: This was appended\n";
print $append "Line 5: And this too!\n";
close($append);

say "Appended 2 more lines. File now contains:";
open(my $read, '<', $outfile) or die "Cannot read: $!\n";
my $ln = 0;
while (<$read>) { $ln++; print "  [$ln] $_" }
close($read);

say "\n=== WRITING FORMATTED DATA ===";

my $report = "$tmpdir/report.txt";
open(my $rpt, '>', $report) or die "Cannot open report: $!\n";

printf $rpt "%-20s %10s %10s %10s\n", "Product", "Q1", "Q2", "Total";
printf $rpt "%s\n", "=" x 52;

my @products = (
    ["Widget Alpha",  15000, 18000],
    ["Widget Beta",   22000, 19500],
    ["Gadget Pro",    31000, 34000],
    ["Gadget Lite",    8500, 12000],
);

for my $product (@products) {
    my ($name, $q1, $q2) = @$product;
    printf $rpt "%-20s %10d %10d %10d\n", $name, $q1, $q2, $q1 + $q2;
}

close($rpt);

say "Formatted report:";
open(my $show, '<', $report) or die "Cannot read report: $!\n";
print "  $_" while <$show>;
close($show);

say "\n=== WRITING WITH HEREDOC ===";

my $html_file = "$tmpdir/page.html";
open(my $html, '>', $html_file) or die "Cannot write HTML: $!\n";

my $title = "Sample Page";
my $body_text = "This HTML was generated by Perl.";

print $html <<HTML;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$title</title>
</head>
<body>
    <h1>$title</h1>
    <p>$body_text</p>
    <p>Generated at: @{[scalar localtime]}</p>
</body>
</html>
HTML

close($html);
say "HTML file written. Size: " . (-s $html_file) . " bytes";

say "\n=== WRITING BINARY / RAW DATA ===";

my $binfile = "$tmpdir/data.bin";
open(my $bin, '>:raw', $binfile) or die "Cannot write binary: $!\n";
print $bin pack("N", 0xDEADBEEF);  # 4-byte big-endian integer
print $bin pack("A10", "Hello");    # 10-byte padded string
print $bin pack("d", 3.14159);      # 8-byte double
close($bin);

say "Binary file written. Size: " . (-s $binfile) . " bytes";

open(my $bread, '<:raw', $binfile) or die "Cannot read binary: $!\n";
my $data;
read($bread, $data, -s $binfile);
close($bread);

my ($magic, $str, $pi) = unpack("N A10 d", $data);
printf "  Magic: 0x%08X\n", $magic;
say "  String: '$str'";
printf "  Pi: %.5f\n", $pi;

say "\n=== DIRECTORY OPERATIONS ===";

my $newdir = "$tmpdir/subdir/nested";
use File::Path qw(make_path);
make_path($newdir);
say "Created directory: $newdir";

opendir(my $dh, $tmpdir) or die "Cannot open dir: $!\n";
my @entries = sort grep { $_ ne '.' && $_ ne '..' } readdir($dh);
closedir($dh);

say "Directory contents:";
for my $entry (@entries) {
    my $path = "$tmpdir/$entry";
    my $type = -d $path ? "DIR " : "FILE";
    printf "  [%s] %s\n", $type, $entry;
}

say "\n--- File writing demo complete ---";
