# ============================================================
# Example 6: SPI Master Interface
# ============================================================
# Design: SPI master communicating with an external ADC/DAC
#
# Interface:
#
#   FPGA (SPI Master)                SPI Slave (e.g., ADC)
#   ┌──────────────────┐            ┌──────────────────┐
#   │                  │            │                  │
#   │  SPI_SCLK ──────│──────────>│  SCLK            │
#   │  SPI_MOSI ──────│──────────>│  MOSI / DIN      │
#   │  SPI_MISO <──────│<──────────│  MISO / DOUT     │
#   │  SPI_CS_N ──────│──────────>│  CS# / SS#       │
#   │                  │            │                  │
#   └──────────────────┘            └──────────────────┘
#
# Timing:
#   System clock: 100 MHz
#   SPI clock: 25 MHz (sys_clk / 4), generated by counter
#
#   SPI Mode 0 (CPOL=0, CPHA=0):
#     - SCLK idles LOW
#     - Data sampled on RISING edge of SCLK
#     - Data changes on FALLING edge of SCLK
#
#   SPI Slave timing (from ADC datasheet):
#     - Tsu (setup to SCLK rising) = 5ns
#     - Th  (hold from SCLK rising) = 5ns
#     - Tco (SCLK falling to MISO valid) = 10ns max, 2ns min
#     - Tv  (MISO valid after CS# falling) = 20ns max
#
# ============================================================

# ============================================================
# Section 1: Clock Definitions
# ============================================================

# 100 MHz system clock
create_clock -name sys_clk -period 10.0 [get_ports SYS_CLK]

derive_clock_uncertainty

# ============================================================
# Section 2: Generated SPI Clock
# ============================================================

# SPI clock generated by a 2-bit counter in the FPGA.
# sys_clk (100 MHz) / 4 = 25 MHz SPI clock.
# The SCLK output toggles on specific counter values.
create_generated_clock -name spi_clk \
    -source [get_ports SYS_CLK] \
    -divide_by 4 \
    [get_ports SPI_SCLK]

# Note: Alternatively, if SCLK is registered:
# create_generated_clock -name spi_clk \
#     -source [get_ports SYS_CLK] \
#     -divide_by 4 \
#     [get_registers {spi_master|sclk_reg}]

# ============================================================
# Section 3: SPI Output Constraints
# ============================================================

# --- MOSI Output ---
# SPI slave samples MOSI on SCLK rising edge.
# Slave Tsu = 5ns, Th = 5ns
# Board trace delay: ~0.5ns
#
# output_delay_max = Tsu + Tboard = 5 + 0.5 = 5.5ns
# output_delay_min = -(Th - Tboard) = -(5 - 0.5) = -4.5ns
#
# SPI period = 40ns, so 40 - 5.5 = 34.5ns available: very relaxed.
set_output_delay -clock spi_clk -max  5.5 [get_ports SPI_MOSI]
set_output_delay -clock spi_clk -min -4.5 [get_ports SPI_MOSI]

# --- Chip Select ---
# CS must be valid before the first SCLK edge.
# Use same timing as MOSI for simplicity.
set_output_delay -clock spi_clk -max  5.5 [get_ports SPI_CS_N]
set_output_delay -clock spi_clk -min -4.5 [get_ports SPI_CS_N]

# ============================================================
# Section 4: SPI Input Constraints
# ============================================================

# --- MISO Input ---
# Slave drives MISO on SCLK falling edge (in Mode 0).
# FPGA samples MISO on the next SCLK rising edge.
# Slave Tco (from falling SCLK) = 10ns max, 2ns min
# Board trace delay: ~0.5ns
#
# The relevant clock edge for sampling is the RISING edge.
# The slave outputs data on the FALLING edge.
# From falling to rising edge = half period = 20ns.
# The data has 20ns - Tco to be valid at the FPGA.
#
# input_delay_max = Tco_max + Tboard = 10 + 0.5 = 10.5ns
# input_delay_min = Tco_min + Tboard = 2 + 0.5 = 2.5ns
#
# Since data changes on the falling edge but is sampled on rising,
# we reference the falling edge:
set_input_delay -clock spi_clk -max 10.5 -clock_fall [get_ports SPI_MISO]
set_input_delay -clock spi_clk -min  2.5 -clock_fall [get_ports SPI_MISO]

# ============================================================
# Section 5: Multicycle Paths
# ============================================================

# SPI clock is 1/4 of system clock. Internal SPI state machine
# runs at sys_clk but only changes state once per SPI clock cycle.
# The MISO sampling register is read by internal logic every 4 sys_clk cycles.
set_multicycle_path 4 -setup \
    -from [get_ports SPI_MISO] \
    -to   [get_registers {spi_master|rx_shift_reg[*]}]
set_multicycle_path 3 -hold \
    -from [get_ports SPI_MISO] \
    -to   [get_registers {spi_master|rx_shift_reg[*]}]

# The SPI TX data register is loaded from sys_clk domain and
# shifted out at SPI rate. No multicycle needed for TX since
# MOSI changes once per SPI cycle and the output_delay
# constraint handles the external timing.

# ============================================================
# Section 6: Timing Exceptions
# ============================================================

# Async reset
set_false_path -from [get_ports RST_N]

# SPI interrupt output (directly drives a status register, no strict timing)
set_false_path -to [get_ports SPI_IRQ_N]
