#!/usr/bin/env tclsh
# =============================================================================
# Example 8: File I/O
# Demonstrates: reading, writing, file operations, CSV processing, temp files
# =============================================================================

puts "=== File I/O ===\n"

set test_dir "/tmp/tcl_file_demo"
file mkdir $test_dir

# --- Writing a file ---
puts "--- Writing Files ---"
set outfile [file join $test_dir "sample.txt"]
set fp [open $outfile w]
puts $fp "Line 1: Hello from TCL!"
puts $fp "Line 2: File I/O is straightforward."
puts $fp "Line 3: This is the third line."
puts $fp "Line 4: TCL makes file handling easy."
puts $fp "Line 5: End of sample file."
close $fp
puts "  Wrote $outfile"

# --- Reading entire file ---
puts "\n--- Reading Entire File ---"
set fp [open $outfile r]
set content [read $fp]
close $fp
puts "  Content:"
puts "  [string map {\n "\n  "} [string trimright $content]]"

# --- Reading line by line ---
puts "\n--- Reading Line by Line ---"
set fp [open $outfile r]
set line_num 0
while {[gets $fp line] >= 0} {
    incr line_num
    puts "  Line $line_num: $line"
}
close $fp

# --- Appending to a file ---
puts "\n--- Appending ---"
set fp [open $outfile a]
puts $fp "Line 6: This line was appended."
close $fp

set fp [open $outfile r]
set lines [split [read $fp] "\n"]
close $fp
puts "  File now has [expr {[llength $lines] - 1}] lines"

# --- File information ---
puts "\n--- File Information ---"
puts "  File exists?  [file exists $outfile]"
puts "  File size:    [file size $outfile] bytes"
puts "  File type:    [file type $outfile]"
puts "  Readable?     [file readable $outfile]"
puts "  Writable?     [file writable $outfile]"
puts "  Extension:    [file extension $outfile]"
puts "  Tail:         [file tail $outfile]"
puts "  Directory:    [file dirname $outfile]"
puts "  Root name:    [file rootname [file tail $outfile]]"

set mtime [file mtime $outfile]
puts "  Modified:     [clock format $mtime -format "%Y-%m-%d %H:%M:%S"]"

# --- Path operations ---
puts "\n--- Path Operations ---"
puts "  join:  [file join "/usr" "local" "bin" "tclsh"]"
puts "  split: [file split "/usr/local/bin/tclsh"]"
puts "  normalize: [file normalize "~/Documents/../Downloads"]"

# --- Writing and reading a CSV file ---
puts "\n--- CSV File Processing ---"
set csvfile [file join $test_dir "employees.csv"]
set fp [open $csvfile w]
puts $fp "Name,Department,Salary,Years"
puts $fp "Alice Johnson,Engineering,95000,5"
puts $fp "Bob Smith,Marketing,75000,3"
puts $fp "Carol Williams,Engineering,105000,8"
puts $fp "David Brown,Sales,68000,2"
puts $fp "Eve Davis,Engineering,88000,4"
close $fp
puts "  Wrote $csvfile"

# Read and process CSV
set fp [open $csvfile r]
gets $fp header
set headers [split $header ","]

set records [list]
while {[gets $fp line] >= 0} {
    if {[string trim $line] eq ""} continue
    set values [split $line ","]
    set record [dict create]
    foreach h $headers v $values {
        dict set record $h $v
    }
    lappend records $record
}
close $fp

puts "\n  Employee Report:"
puts [format "  %-18s %-15s %10s %5s" {*}$headers]
puts "  [string repeat - 55]"
foreach rec $records {
    puts [format "  %-18s %-15s %10s %5s" \
        [dict get $rec Name] \
        [dict get $rec Department] \
        [dict get $rec Salary] \
        [dict get $rec Years]]
}

# Summary statistics
set total_salary 0
set eng_count 0
foreach rec $records {
    set total_salary [expr {$total_salary + [dict get $rec Salary]}]
    if {[dict get $rec Department] eq "Engineering"} {
        incr eng_count
    }
}
set avg_salary [expr {$total_salary / [llength $records]}]
puts "\n  Total employees: [llength $records]"
puts "  Engineers: $eng_count"
puts [format "  Average salary: \$%d" $avg_salary]

# --- Writing a configuration file ---
puts "\n--- Config File ---"
set cfgfile [file join $test_dir "app.conf"]
set config [dict create \
    host "localhost" \
    port 8080 \
    debug true \
    log_level "info" \
    max_connections 100 \
]

set fp [open $cfgfile w]
puts $fp "# Application Configuration"
puts $fp "# Generated by TCL script"
puts $fp ""
dict for {key value} $config {
    puts $fp "$key = $value"
}
close $fp
puts "  Wrote $cfgfile"

# Read it back
set fp [open $cfgfile r]
puts "  Contents:"
while {[gets $fp line] >= 0} {
    puts "    $line"
}
close $fp

# --- File glob (finding files) ---
puts "\n--- File Globbing ---"
set files [glob -nocomplain -directory $test_dir *]
puts "  Files in $test_dir:"
foreach f [lsort $files] {
    puts [format "    %-25s %d bytes" [file tail $f] [file size $f]]
}

# --- Cleanup ---
puts "\n--- Cleanup ---"
foreach f [glob -directory $test_dir *] {
    file delete $f
}
file delete $test_dir
puts "  Removed test directory and files."

puts "\nDone."
