# ==============================================================
# Example 08: Source-Synchronous RGMII (Gigabit Ethernet)
# ==============================================================
# Scenario:
#   - Gigabit Ethernet PHY connected via RGMII
#   - RGMII clock: 125 MHz (8 ns period)
#   - Data is DDR: 4-bit data bus × 2 edges = 8 bits/cycle
#   - RX path: PHY sends rgmii_rx_clk + rgmii_rxd[3:0]
#              + rgmii_rx_ctl (center-aligned clock)
#   - TX path: FPGA sends rgmii_tx_clk + rgmii_txd[3:0]
#              + rgmii_tx_ctl
#   - System clock: 50 MHz on CLK_50
# ==============================================================

# ----------------------------------------------------------
# 1. System clock
# ----------------------------------------------------------
create_clock -name sys_clk -period 20.0 [get_ports CLK_50]
derive_pll_clocks
derive_clock_uncertainty

# ----------------------------------------------------------
# 2. RGMII RX clock (from PHY)
# ----------------------------------------------------------
# This is a source-synchronous clock that arrives on the
# FPGA together with the data.
create_clock -name rgmii_rx_clk -period 8.0 [get_ports rgmii_rx_clk]

# ----------------------------------------------------------
# 3. RX data input constraints
# ----------------------------------------------------------
# RGMII spec: data is center-aligned with the clock.
# Valid window: ±1.0 ns around both rising and falling edges.
#
# max input delay =  1.0 ns (data arrives up to 1 ns after edge)
# min input delay = -1.0 ns (data arrives up to 1 ns before edge)

# Rising edge
set_input_delay -clock rgmii_rx_clk -max  1.0 [get_ports {rgmii_rxd[*] rgmii_rx_ctl}]
set_input_delay -clock rgmii_rx_clk -min -1.0 [get_ports {rgmii_rxd[*] rgmii_rx_ctl}]

# Falling edge (DDR)
set_input_delay -clock rgmii_rx_clk -max  1.0 -clock_fall -add_delay [get_ports {rgmii_rxd[*] rgmii_rx_ctl}]
set_input_delay -clock rgmii_rx_clk -min -1.0 -clock_fall -add_delay [get_ports {rgmii_rxd[*] rgmii_rx_ctl}]

# ----------------------------------------------------------
# 4. RGMII TX clock (generated by FPGA, forwarded to PHY)
# ----------------------------------------------------------
# TX clock is generated by a PLL with a 90° phase shift
# relative to the internal data clock, so that data is
# centered at the PHY's sampling point.
#
# If derive_pll_clocks created the TX PLL output, use that
# clock name.  Otherwise, create a virtual clock for
# constraining the TX data:

create_clock -name virt_rgmii_tx_clk -period 8.0

# ----------------------------------------------------------
# 5. TX data output constraints
# ----------------------------------------------------------
# RGMII spec: the PHY samples data ±1.0 ns around
# its clock edge.  The FPGA must deliver data within
# this window.

# Rising edge
set_output_delay -clock virt_rgmii_tx_clk -max  1.0 [get_ports {rgmii_txd[*] rgmii_tx_ctl}]
set_output_delay -clock virt_rgmii_tx_clk -min -1.0 [get_ports {rgmii_txd[*] rgmii_tx_ctl}]

# Falling edge (DDR)
set_output_delay -clock virt_rgmii_tx_clk -max  1.0 -clock_fall -add_delay [get_ports {rgmii_txd[*] rgmii_tx_ctl}]
set_output_delay -clock virt_rgmii_tx_clk -min -1.0 -clock_fall -add_delay [get_ports {rgmii_txd[*] rgmii_tx_ctl}]

# ----------------------------------------------------------
# 6. TX clock output — false path
# ----------------------------------------------------------
# rgmii_tx_clk is a forwarded clock, not data.
set_false_path -to [get_ports rgmii_tx_clk]

# ----------------------------------------------------------
# 7. Clock groups
# ----------------------------------------------------------
# System clock, RX domain, and TX domain are all asynchronous.
set_clock_groups -asynchronous \
    -group [get_clocks {sys_clk}] \
    -group [get_clocks {rgmii_rx_clk}] \
    -group [get_clocks {virt_rgmii_tx_clk}]

# ----------------------------------------------------------
# 8. Ethernet PHY reset — asynchronous, no timing
# ----------------------------------------------------------
set_false_path -to [get_ports phy_rst_n]

# ----------------------------------------------------------
# 9. MDIO management interface — very slow, false path
# ----------------------------------------------------------
set_false_path -to   [get_ports {mdio mdc}]
set_false_path -from [get_ports mdio]
