# ==============================================================================
# SDC Timing Constraints for Macronix MX66U1G45G 1.8V 1Gb SPI NOR Flash
# Target: Altera (Intel) FPGA — Quartus Prime TimeQuest Timing Analyzer
#
# Device:   MX66U1G45G (BGA-24 package, J-Grade: -40°C to 105°C)
# Datasheet: Rev 1.2, August 13, 2020
# Interface: SPI Mode 0 (CPOL=0, CPHA=0) / Mode 3 (CPOL=1, CPHA=1)
# Modes:    Standard SPI (x1), Dual I/O (x2), Quad I/O (x4), STR & DTR
#
# IMPORTANT: Adapt port names and clock sources to match your RTL design.
# ==============================================================================


# ==============================================================================
# Section 1: User-Configurable Parameters
# ==============================================================================

# ---- Flash AC Timing from MX66U1G45G Datasheet (Table 19) ----

# Clock-to-output valid (Flash → FPGA read path), max values
# Select the value matching your PCB loading:
#   30 pF loading : 8.0 ns
#   15 pF loading : 6.0 ns  (16-SOP; BGA-24 expected ≤ 6.0 ns)
#   10 pF loading : 6.0 ns
set tCLQV_max        7.0   ;# Conservative default for ~15-20 pF typical PCB loading

# Output hold time (Flash → FPGA read path), min value
set tCLQX_min        1.0   ;# Min 1.0 ns (typ 3.0 ns)

# Data-in setup time (FPGA → Flash write path), STR mode
set tDVCH            1.5   ;# Min 1.5 ns

# Data-in hold time (FPGA → Flash write path), STR mode
set tCHDX            1.5   ;# Min 1.5 ns

# Data-in setup time (FPGA → Flash write path), DTR mode
set tDVCL            1.5   ;# Min 1.5 ns

# Data-in hold time (FPGA → Flash write path), DTR mode
set tCLDX            1.5   ;# Min 1.5 ns

# CS# active setup time relative to SCLK rising edge
set tSLCH            4.5   ;# Min 4.5 ns

# CS# not-active hold time relative to SCLK rising edge
set tCHSL            4.0   ;# Min 4.0 ns

# CS# active hold time relative to SCLK rising edge
set tCHSH            3.0   ;# Min 3.0 ns

# CS# deselect time (read-to-read)
set tSHSL_read       7.0   ;# Min 7.0 ns

# CS# deselect time (write/erase/program to read status register)
set tSHSL_write     30.0   ;# Min 30.0 ns

# Output disable time (CS# high to outputs Hi-Z)
set tSHQZ            5.5   ;# Max 5.5 ns (BGA-24, 15 pF)


# ---- Board-Level Trace Delays ----
# Adjust these to match your PCB design. For matched-length traces, set both
# to the same value. Units: nanoseconds.

set board_delay_clk_min   0.1   ;# Min propagation delay: FPGA SCLK pin → Flash CLK pin
set board_delay_clk_max   0.3   ;# Max propagation delay: FPGA SCLK pin → Flash CLK pin
set board_delay_data_min  0.1   ;# Min propagation delay: data trace (either direction)
set board_delay_data_max  0.3   ;# Max propagation delay: data trace (either direction)


# ---- SPI Clock Configuration ----
# Maximum operating frequencies from datasheet:
#   Normal READ (1-1-1):       50 MHz
#   FAST READ / DREAD / 2READ: up to 133 MHz (6 dummy cycles)
#   4READ / QREAD / 4DTRD:    up to 166 MHz (10 dummy cycles)
#
# Set spi_clk_period to match your design's SPI clock frequency.
set spi_clk_period  20.0  ;# 50 MHz default (ns). Adjust as needed.


# ---- FPGA Port Names ----
# Change these to match your design's top-level port names.
set flash_sclk_port     FLASH_SCLK
set flash_cs_n_port     FLASH_CS_N
set flash_mosi_port     FLASH_MOSI     ;# SIO0
set flash_miso_port     FLASH_MISO     ;# SIO1

# For Dual I/O mode, add SIO[1] as bidirectional:
set flash_sio1_port     FLASH_SIO1     ;# Same as MISO in standard SPI

# For Quad I/O mode, add SIO[0:3]:
set flash_sio_ports     {FLASH_SIO0 FLASH_SIO1 FLASH_SIO2 FLASH_SIO3}

# ---- Clock Source ----
# Specify how SCLK is generated in your design. Uncomment ONE option:
#   Option A: SCLK from a PLL output driving a register, divided by N
#   Option B: SCLK toggled by a register clocked by sys_clk
#   Option C: SCLK from ALTDDIO_OUT (DDR output) for higher frequencies
set spi_clk_source_pin  "spi_master_inst|spi_clk_reg|q"  ;# Register output driving SCLK


# ==============================================================================
# Section 2: System Clock
# ==============================================================================

# Define the primary system clock feeding the SPI controller.
# Adjust period and port name to match your design.
# If the system clock is already constrained elsewhere, remove this line.
#
# create_clock -name sys_clk -period 10.0 [get_ports {SYS_CLK}]


# ==============================================================================
# Section 3: SPI Clock — Generated Clock on SCLK Output Pin
# ==============================================================================

# Create a generated clock at the FPGA's SCLK output pin.
# This represents the clock as seen by the external flash at the FPGA boundary.
#
# Option A: SCLK generated by a clock divider register
#   -divide_by N should match your RTL's clock division ratio.
create_generated_clock \
    -name spi_sclk \
    -source [get_pins $spi_clk_source_pin] \
    -divide_by 1 \
    [get_ports $flash_sclk_port]

# Option B (alternative): SCLK from PLL output through a DDR output buffer
# Uncomment and adapt if using ALTDDIO_OUT or similar:
#
# create_generated_clock \
#     -name spi_sclk \
#     -source [get_pins {pll_inst|outclk_0}] \
#     [get_ports $flash_sclk_port]


# ==============================================================================
# Section 4: Virtual Clock for Flash Interface
# ==============================================================================

# A virtual clock representing the SPI clock at the flash device,
# accounting for board-level propagation delay.
# Used as a timing reference for input/output delay constraints.

create_clock -name spi_sclk_virtual -period $spi_clk_period


# ==============================================================================
# Section 5: Output Constraints — FPGA → Flash (Write Path: MOSI, CS#)
# ==============================================================================
# In SPI Mode 0, the FPGA drives MOSI on the falling edge of SCLK and the
# flash latches it on the rising edge. CS# transitions are also relative to
# SCLK edges.
#
# Output delay formula (source-synchronous):
#   -max = tsu_flash + Tbd_max - Tbc_min    (setup analysis)
#   -min = -(th_flash) + Tbd_min - Tbc_max  (hold analysis)
#
# Where:
#   tsu_flash = flash data setup time (tDVCH for data, tSLCH for CS#)
#   th_flash  = flash data hold time  (tCHDX for data, tCHSL for CS# approx)
#   Tbd       = board delay on data path
#   Tbc       = board delay on clock path
# ==============================================================================

# ---- 5a: MOSI / SIO0 Output Delay (Standard SPI Mode) ----

set mosi_output_delay_max [expr {$tDVCH + $board_delay_data_max - $board_delay_clk_min}]
set mosi_output_delay_min [expr {-$tCHDX + $board_delay_data_min - $board_delay_clk_max}]

set_output_delay \
    -clock spi_sclk \
    -max $mosi_output_delay_max \
    [get_ports $flash_mosi_port]

set_output_delay \
    -clock spi_sclk \
    -min $mosi_output_delay_min \
    [get_ports $flash_mosi_port]


# ---- 5b: CS# Output Delay ----
# CS# must be asserted tSLCH before SCLK rising edge and held tCHSL after.

set cs_output_delay_max [expr {$tSLCH + $board_delay_data_max - $board_delay_clk_min}]
set cs_output_delay_min [expr {-$tCHSL + $board_delay_data_min - $board_delay_clk_max}]

set_output_delay \
    -clock spi_sclk \
    -max $cs_output_delay_max \
    [get_ports $flash_cs_n_port]

set_output_delay \
    -clock spi_sclk \
    -min $cs_output_delay_min \
    [get_ports $flash_cs_n_port]


# ---- 5c: Quad I/O Output Delay (SIO[0:3] in output mode) ----
# Apply the same data output constraints to all SIO pins when used for writes.
# Uncomment the block below if your design uses Quad I/O mode.

# foreach sio_port $flash_sio_ports {
#     set_output_delay \
#         -clock spi_sclk \
#         -max $mosi_output_delay_max \
#         [get_ports $sio_port]
#
#     set_output_delay \
#         -clock spi_sclk \
#         -min $mosi_output_delay_min \
#         [get_ports $sio_port]
# }


# ==============================================================================
# Section 6: Input Constraints — Flash → FPGA (Read Path: MISO)
# ==============================================================================
# The flash drives data on the FALLING edge of SCLK. The FPGA captures data
# on the RISING edge (half a period later in Mode 0).
#
# Input delay formula (source-synchronous, data launched on falling edge):
#   -max = Tbc_max + tCLQV_max + Tbd_max   (setup analysis)
#   -min = Tbc_min + tCLQX_min + Tbd_min   (hold analysis)
#
# The -clock_fall flag indicates the flash launches data on the falling edge.
# TimeQuest will then check setup against the next rising edge (half period
# later) and hold against the same falling edge.
# ==============================================================================

set miso_input_delay_max [expr {$board_delay_clk_max + $tCLQV_max + $board_delay_data_max}]
set miso_input_delay_min [expr {$board_delay_clk_min + $tCLQX_min + $board_delay_data_min}]

set_input_delay \
    -clock spi_sclk \
    -clock_fall \
    -max $miso_input_delay_max \
    [get_ports $flash_miso_port]

set_input_delay \
    -clock spi_sclk \
    -clock_fall \
    -min $miso_input_delay_min \
    [get_ports $flash_miso_port]


# ---- 6a: Quad I/O Input Delay (SIO[0:3] in input mode) ----
# Uncomment the block below if your design uses Quad I/O mode.

# foreach sio_port $flash_sio_ports {
#     set_input_delay \
#         -clock spi_sclk \
#         -clock_fall \
#         -max $miso_input_delay_max \
#         [get_ports $sio_port]
#
#     set_input_delay \
#         -clock spi_sclk \
#         -clock_fall \
#         -min $miso_input_delay_min \
#         [get_ports $sio_port]
# }


# ==============================================================================
# Section 7: DTR (Double Transfer Rate) Mode Constraints
# ==============================================================================
# In DTR mode, data is driven and captured on BOTH edges of SCLK.
# The flash launches data on both rising and falling edges.
# Uncomment this section if your design uses DTR mode (4DTRD command).
#
# Supported up to 166 MHz with 10 dummy cycles.
# ==============================================================================

# set dtr_output_delay_max [expr {$tDVCL + $board_delay_data_max - $board_delay_clk_min}]
# set dtr_output_delay_min [expr {-$tCLDX + $board_delay_data_min - $board_delay_clk_max}]
# set dtr_input_delay_max  [expr {$board_delay_clk_max + $tCLQV_max + $board_delay_data_max}]
# set dtr_input_delay_min  [expr {$board_delay_clk_min + $tCLQX_min + $board_delay_data_min}]
#
# # Output constraints for DTR — both edges
# foreach sio_port $flash_sio_ports {
#     set_output_delay -clock spi_sclk -max $dtr_output_delay_max \
#         [get_ports $sio_port]
#     set_output_delay -clock spi_sclk -max $dtr_output_delay_max \
#         -clock_fall -add_delay [get_ports $sio_port]
#
#     set_output_delay -clock spi_sclk -min $dtr_output_delay_min \
#         [get_ports $sio_port]
#     set_output_delay -clock spi_sclk -min $dtr_output_delay_min \
#         -clock_fall -add_delay [get_ports $sio_port]
# }
#
# # Input constraints for DTR — data launched on both edges
# foreach sio_port $flash_sio_ports {
#     set_input_delay -clock spi_sclk -max $dtr_input_delay_max \
#         [get_ports $sio_port]
#     set_input_delay -clock spi_sclk -max $dtr_input_delay_max \
#         -clock_fall -add_delay [get_ports $sio_port]
#
#     set_input_delay -clock spi_sclk -min $dtr_input_delay_min \
#         [get_ports $sio_port]
#     set_input_delay -clock spi_sclk -min $dtr_input_delay_min \
#         -clock_fall -add_delay [get_ports $sio_port]
# }


# ==============================================================================
# Section 8: Bus Contention Prevention — TX→RX Turnaround on SIO[0:3]
# ==============================================================================
# CRITICAL: In Dual/Quad I/O modes, SIO lines are bidirectional. During read
# commands (2READ, 4READ, QREAD, 4DTRD), the FPGA first drives SIO[0:3] with
# command/address, then the flash drives SIO[0:3] with read data. A
# "turnaround" must occur between these phases.
#
# WHAT HAPPENS IF BOTH DRIVE SIMULTANEOUSLY (BUS CONTENTION):
#
#   1. SHOOT-THROUGH CURRENT: When the FPGA drives a pin HIGH while the flash
#      drives it LOW (or vice versa), a low-impedance path forms from VCC to
#      GND through both output stages. At 1.8 V with ~50 Ω driver impedance
#      per side, this draws ~18 mA per pin. In Quad mode all 4 SIO pins may
#      contend simultaneously → up to ~72 mA of wasted current on a 1.8 V
#      rail. This causes localized heating in both the FPGA I/O bank and the
#      flash die.
#
#   2. INDETERMINATE VOLTAGE: The SIO line settles at a voltage divider
#      midpoint (~VCC/2 ≈ 0.9 V) which falls in the "forbidden zone" between
#      VIL_max (0.35×VCC ≈ 0.63 V) and VIH_min (0.65×VCC ≈ 1.17 V). This
#      causes:
#        - Metastability in the FPGA input register (the input buffer sees
#          neither a clean 0 nor a clean 1)
#        - Excessive CMOS static current in both the FPGA and flash input
#          buffers (both PMOS and NMOS partially conduct)
#        - The first captured data byte will be corrupted
#
#   3. VCC DROOP / GROUND BOUNCE: The sudden current spike during contention
#      causes transient droops on VCC and ground bounce on VSS. On a 1.8 V
#      rail with 72 mA spike through ~2 nH package inductance at a ~1 ns edge:
#        ΔV = L × dI/dt ≈ 2 nH × 72 mA / 1 ns ≈ 144 mV
#      This 144 mV noise can:
#        - Corrupt data on OTHER SIO lines (crosstalk through shared VCC/GND)
#        - Cause glitches on adjacent FPGA I/O bank pins
#        - Disturb the flash's internal state machine operation
#
#   4. SIGNAL RINGING AFTER CONTENTION: When one driver finally releases
#      (tristates), the stored energy in the PCB trace inductance causes
#      ringing (underdamped LC oscillation). This ringing can persist for
#      2–5 ns and may violate tDVCH/tCHDX setup/hold windows at the flash
#      or tCLQV/tCLQX timing at the FPGA on the next valid data edge.
#
#   5. LONG-TERM RELIABILITY DEGRADATION: Repeated contention events
#      accelerate electromigration in metal traces and hot-carrier injection
#      in I/O transistors. The device won't fail immediately but its lifetime
#      degrades — particularly problematic for industrial/automotive designs
#      that must meet 10+ year reliability targets.
#
# PROTOCOL-LEVEL TURNAROUND (from MX66U1G45G datasheet):
#   - In 4READ (SPI mode): After 6 address cycles on SIO[0:3], there are
#     2 "performance enhance indicator" cycles (still FPGA-driven), then
#     configurable dummy cycles (default 6, adjustable 4–10). The flash
#     begins driving on the first data-out cycle AFTER the dummy phase.
#   - In QREAD (SPI mode): Command on SIO0 → address on SIO0 → dummy
#     cycles → data out on SIO[0:3]. Only SIO0 needs turnaround.
#   - In 4DTRD (DTR mode): Same as 4READ but data on both clock edges.
#
# RTL DESIGN REQUIREMENT:
#   The FPGA must tristate (Hi-Z) its SIO output enables AT LEAST 1 full
#   SCLK cycle before the flash begins driving. The dummy cycles exist
#   precisely to provide this turnaround window.
#
#   Recommended: Deassert OE on the clock edge that begins the FIRST dummy
#   cycle, giving (N_dummy × T_sclk_period) of dead time before the flash
#   drives. For 4READ with 6 dummy cycles at 133 MHz, this is ~45 ns.
#
# SDC CONSTRAINTS FOR THE OE TURNAROUND PATH:
# The output-enable control path from the SPI state machine to the SIO
# tristate buffers must meet timing so that OE deasserts in the correct
# SCLK cycle. Constrain this path with set_max_delay to prevent OE from
# arriving late and causing contention.
# ==============================================================================

# ---- 8a: Output Enable Timing for SIO Tristate Control ----
# The OE deassert must propagate from the SPI controller's state machine
# register to the I/O output-enable pin within one SCLK period.
#
# Adjust the register path to match your RTL. The -from register is the
# flip-flop that controls whether SIO is driven, and -to is the OE pin
# of the I/O buffer.
#
# set_max_delay -from [get_registers {spi_master_inst|sio_oe_reg[*]}] \
#               -to   [get_ports $flash_sio_ports] \
#               [expr {$spi_clk_period - 1.0}]
#
# The "-1.0" margin ensures OE deasserts at least 1 ns before the next
# clock edge, accounting for FPGA tristate buffer delay (tZX typically
# 2–5 ns on Altera devices).

# ---- 8b: False-Path the Turnaround Cycle Data ----
# During the dummy/turnaround cycles, the data on SIO lines is don't-care.
# Both input and output data paths are meaningless during this window.
# If your RTL has a "turnaround" or "dummy_phase" state signal, you can
# mark it as a false path to prevent Quartus from over-constraining:
#
# set_false_path -from [get_registers {spi_master_inst|is_turnaround_reg}] \
#                -to   [get_ports $flash_sio_ports]

# ---- 8c: OE and Data Mutual Exclusion ----
# The SIO bidirectional ports have both input and output delay constraints
# (Sections 5 and 6). Quartus must understand that input constraints apply
# only when the FPGA is receiving (OE deasserted), and output constraints
# only when the FPGA is driving (OE asserted). This is inherently handled
# by Altera bidir I/O cell analysis — no extra SDC is needed. However, if
# you see spurious timing violations on SIO ports, verify that the I/O
# standard is set to bidirectional in the QSF:
#
#   set_instance_assignment -name IO_STANDARD "1.8 V" -to FLASH_SIO0
#   set_instance_assignment -name IO_STANDARD "1.8 V" -to FLASH_SIO1
#   set_instance_assignment -name IO_STANDARD "1.8 V" -to FLASH_SIO2
#   set_instance_assignment -name IO_STANDARD "1.8 V" -to FLASH_SIO3

# ---- 8d: Minimum Tristate Dead Time Check ----
# Post-synthesis, verify in the TimeQuest timing report that the OE
# deassert path meets the following requirement:
#
#   OE_deassert_delay + tZX(FPGA) < T_sclk_period
#
# Where tZX is the FPGA's tristate-to-high-impedance time (~2–5 ns).
# Run this report after compilation:
#
#   report_timing -from [get_registers {*sio_oe*}] -to [get_ports {FLASH_SIO*}] -npaths 10
#
# If the slack is negative, the OE is arriving too late and bus contention
# WILL occur on every read transaction.


# ==============================================================================
# Section 9: Multicycle Path Constraints
# ==============================================================================
# SPI interfaces often operate at a much slower frequency than the FPGA fabric.
# If the SPI controller uses multicycle enables or the SCLK is divided from a
# faster internal clock, add multicycle path exceptions here.
#
# Example: If SCLK = sys_clk / 4, the SPI data changes once every 4 sys_clk
# cycles. Add a 4-cycle multicycle path to relax internal timing:
#
# set_multicycle_path -setup -from [get_clocks sys_clk] -to [get_clocks spi_sclk] 4
# set_multicycle_path -hold  -from [get_clocks sys_clk] -to [get_clocks spi_sclk] 3


# ==============================================================================
# Section 10: False Path Constraints
# ==============================================================================
# Static or quasi-static control signals that do not need to be timed at
# full SPI clock speed.

# CS# deselect: The CS# signal is asserted/deasserted asynchronously relative
# to SCLK between transactions. If your design handles CS# outside the SPI
# clock domain, mark it as a false path to avoid spurious timing violations
# during idle periods.
#
# set_false_path -from [get_registers {*spi*cs_idle*}] -to [get_ports $flash_cs_n_port]

# Clock-domain crossings: If the SPI controller crosses between sys_clk and
# spi_sclk domains with synchronizers, mark those paths:
#
# set_false_path -from [get_clocks sys_clk] -to [get_clocks spi_sclk]
# set_false_path -from [get_clocks spi_sclk] -to [get_clocks sys_clk]
#
# Or more precisely, if using proper synchronizer chains:
# set_max_delay -from [get_registers {*cdc_sync_reg[0]*}] <sync_chain_delay>


# ==============================================================================
# Section 11: Clock Uncertainty and Jitter
# ==============================================================================
# Add clock uncertainty to account for SCLK jitter from PLL or register-based
# clock generation. Quartus applies default uncertainty, but explicit values
# improve accuracy.

set_clock_uncertainty -setup 0.1 [get_clocks spi_sclk]
set_clock_uncertainty -hold  0.05 [get_clocks spi_sclk]

set_clock_uncertainty -setup 0.1 [get_clocks spi_sclk_virtual]
set_clock_uncertainty -hold  0.05 [get_clocks spi_sclk_virtual]


# ==============================================================================
# Section 12: Timing Margin Report
# ==============================================================================
# Summary of timing budget at the default 50 MHz (20 ns period):
#
# --- Read Path (Flash → FPGA, MISO) ---
# Setup check (rising edge capture, data launched on falling edge):
#   Available window  = half_period - input_delay_max
#                     = 10.0 - (0.3 + 7.0 + 0.3) = 2.4 ns
#   This must be > FPGA input register tsu (~0.5 ns typical)
#   Margin ≈ 1.9 ns  ✓
#
# Hold check:
#   input_delay_min   = 0.1 + 1.0 + 0.1 = 1.2 ns
#   This must be > FPGA input register th (~0.3 ns typical)
#   Margin ≈ 0.9 ns  ✓
#
# --- Write Path (FPGA → Flash, MOSI) ---
# Setup check:
#   Available window  = half_period - output_delay_max
#                     = 10.0 - (1.5 + 0.3 - 0.1) = 8.3 ns
#   This must be > FPGA output register tco (~0.5 ns typical)
#   Margin ≈ 7.8 ns  ✓
#
# Hold check:
#   output_delay_min  = -(1.5) + 0.1 - 0.3 = -1.7 ns (negative → relaxed)
#   Margin is comfortable  ✓
#
# At 133 MHz (7.5 ns period, 3.75 ns half-period):
#   Read setup margin = 3.75 - 7.6 = -3.85 ns  ✗ (FAILS — need faster
#     sampling strategy, e.g., PLL phase shift, DDIO input, or slower clock)
#
# Recommendation: For clock frequencies above ~66 MHz, use PLL-based clock
# phase shifting or ALTDDIO_IN to center-align the capture edge with the
# incoming data window.
#
# ==============================================================================

puts "INFO: MX66U1G45G SDC constraints loaded successfully."
puts "INFO: SPI clock period = $spi_clk_period ns ([expr {1000.0 / $spi_clk_period}] MHz)"
puts "INFO: Read path input delay max  = $miso_input_delay_max ns"
puts "INFO: Read path input delay min  = $miso_input_delay_min ns"
puts "INFO: Write path output delay max = $mosi_output_delay_max ns"
puts "INFO: Write path output delay min = $mosi_output_delay_min ns"
